// Code generated by tygo. DO NOT EDIT.
import * as uuid from "uuid"

//////////
// source: auth.service.go

export const PASSWORD_HASH_ALGO_ID = "argon2id";
export const PASSWORD_HASH_HASH_LENGTH_BYTES = 512;
export const PASSWORD_HASH_SALT_LENGTH_BYTES = 64;
export const PASSWORD_HASH_ITERATIONS = 2;
export const PASSWORD_HASH_MEMORY = 64 * 1024;
export const PASSWORD_HASH_PARALLELISM = 4;
export interface AuthService {
}
export const JWT_SESSION_ID_KEY = "session_id";

//////////
// source: user.service.go

export const APP_EMAIL_URL_KEY = "app:email:url";
export const APP_EMAIL_USERNAME_KEY = "app:email:username";
export const APP_EMAIL_PASSWORD_KEY = "app:email:password";
export const APP_EMAIL_FROM_KEY = "app:email:from";
export type UserRole = string;
export const USER_ROLE_OWNER: UserRole = "owner";
export const USER_ROLE_ADMIN: UserRole = "admin";
export const USER_ROLE_USER: UserRole = "user";
export type AccountStatus = string;
export const ACCOUNT_STATUS_ACTIVE: AccountStatus = "active";
export const ACCOUNT_STATUS_DISABLED: AccountStatus = "disabled";
export interface UserService {
}
export interface User {
  Id: uuid.UUIDTypes;
  AccountStatus: AccountStatus;
  Email: string;
  Name: string;
  Role: UserRole;
}
export interface UserCreate {
  Email: string;
  Name: string;
  Password: string;
  Role: string;
}
