// Code generated by tygo. DO NOT EDIT.
import * as uuid from "uuid"

//////////
// source: auth.service.go

export const PASSWORD_HASH_ALGO_ID = "argon2id";
export const PASSWORD_HASH_HASH_LENGTH_BYTES = 512;
export const PASSWORD_HASH_SALT_LENGTH_BYTES = 64;
export const PASSWORD_HASH_ITERATIONS = 2;
export const PASSWORD_HASH_MEMORY = 64 * 1024;
export const PASSWORD_HASH_PARALLELISM = 4;
export interface AuthService {
}
export const JWT_SESSION_ID_KEY = "session_id";

//////////
// source: data.service.go

export type DataType = string;
export const DATA_TYPE_STRING: DataType = "string";
export const DATA_TYPE_INT: DataType = "int";
export const DATA_TYPE_UINT: DataType = "uint";
export const DATA_TYPE_FLOAT: DataType = "float";
export const DATA_TYPE_BOOLEAN: DataType = "boolean";
export const DATA_TYPE_TIMESTAMP: DataType = "timestamp";
export type SaveDataHierarchy = string;
export const SAVE_DATA_HIERARCHY_DATA_SCHEMA: SaveDataHierarchy = "data_schema";
export const SAVE_DATA_HIERARCHY_SAMPLE: SaveDataHierarchy = "sample";
export interface DataService {
}
export interface ColumnSchema {
  label: string;
  dtype: DataType;
}
export type DataStorage = string;
export const DATA_STORAGE_INTERNAL: DataStorage = "internal";
export const DATA_STORAGE_EXTERNAL: DataStorage = "external";
export interface DataSchema {
  Id: uuid.UUIDTypes;
  Creator: uuid.UUIDTypes;
  Schema: ColumnSchema[];
  Storage: DataStorage;
  Label: string;
  Description: string;
}

//////////
// source: project.service.go

export type ProjectUserPermission = string;
export const PROJECT_USER_PERMISSION_READ: ProjectUserPermission = "read";
export const PROJECT_USER_PERMISSION_READ_WRITE: ProjectUserPermission = "read_write";
export const PROJECT_USER_PERMISSION_ADMIN: ProjectUserPermission = "admin";
export const PROJECT_USER_PERMISSION_OWNER: ProjectUserPermission = "owner";
export type Visibility = string;
export const VISIBILITY_PUBLIC: Visibility = "public";
export const VISIBILITY_PRIVATE: Visibility = "private";
export type SampleUserPermission = string;
export const SAMPLE_USER_PERMISSION_OWNER: SampleUserPermission = "owner";
export const SAMPLE_USER_PERMISSION_READ: SampleUserPermission = "read";
export const SAMPLE_USER_PERMISSION_ADD_DATA: SampleUserPermission = "add_data";
export const SAMPLE_USER_PERMISSION_CREATE_NOTE: SampleUserPermission = "create_note";
export const SAMPLE_USER_PERMISSION_MODIFY_PROPERTIES: SampleUserPermission = "modify_properties";
export interface ProjectService {
}
export interface Project {
  Id: uuid.UUIDTypes;
  Creator: uuid.UUIDTypes;
  Label: string;
  Description: string;
  Visibility: Visibility;
}

//////////
// source: user.service.go

export const APP_EMAIL_URL_KEY = "app:email:url";
export const APP_EMAIL_USERNAME_KEY = "app:email:username";
export const APP_EMAIL_PASSWORD_KEY = "app:email:password";
export const APP_EMAIL_FROM_KEY = "app:email:from";
export type UserRole = string;
export const USER_ROLE_OWNER: UserRole = "owner";
export const USER_ROLE_ADMIN: UserRole = "admin";
export const USER_ROLE_USER: UserRole = "user";
export type AccountStatus = string;
export const ACCOUNT_STATUS_ACTIVE: AccountStatus = "active";
export const ACCOUNT_STATUS_DISABLED: AccountStatus = "disabled";
export interface UserService {
}
export interface User {
  Id: uuid.UUIDTypes;
  AccountStatus: AccountStatus;
  Email: string;
  Name: string;
  Role: UserRole;
}
export interface UserCreate {
  Email: string;
  Name: string;
  Password: string;
  Role: string;
}
