// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AppConfigGet(): $CancellablePromise<$models.AppConfig> {
    return $Call.ByID(3610881243).then(($result: any) => {
        return $$createType0($result);
    });
}

export function AppConfigLoad(): $CancellablePromise<$models.Ok> {
    return $Call.ByID(3320918005).then(($result: any) => {
        return $$createType1($result);
    });
}

export function AppConfigSave(config: $models.AppConfig): $CancellablePromise<$models.Ok> {
    return $Call.ByID(448852716, config).then(($result: any) => {
        return $$createType1($result);
    });
}

function AppState(): $CancellablePromise<$models.AppState | null> {
    return $Call.ByID(812335020).then(($result: any) => {
        return $$createType3($result);
    });
}

export function DatabaseConnect(): $CancellablePromise<$models.Ok> {
    return $Call.ByID(1954003937).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = $models.AppConfig.createFrom;
const $$createType1 = $models.Ok.createFrom;
const $$createType2 = $models.AppState.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
