// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function OpenFileDialogSingle(title: string, filters: $models.FileFilter[]): $CancellablePromise<string> {
    return $Call.ByID(3186687502, title, filters);
}

/**
 * SaveFileSingle prompts a user for a save path for the given data.
 * If a file already exists at the chosen path, they are prompted to confirm they wish to overwrite the existing data.
 * Returns the path the user selected.
 */
export function SaveFileSingle(data: string, title: string, filters: $models.FileFilter[]): $CancellablePromise<string> {
    return $Call.ByID(53312859, data, title, filters);
}
