// Code generated by tygo. DO NOT EDIT.
import * as uuid from "uuid"

//////////
// source: errors.go

export interface AppError {
  Code: AppErrorCode;
  Message: string;
  Payload: any;
}
export type AppErrorCode = string;
export const AppErrCodeEmailNotSent: AppErrorCode = "USER_EMAIL_NOT_SENT";
export const AppErrorCodeUserNotAuthenticated: AppErrorCode = "USER_NOT_AUTHENTICATED";
export const AppErrorCodeRecordNotFound: AppErrorCode = "RECORD_NOT_FOUND";
export const AppErrorCodeInvalidPassword: AppErrorCode = "INVALID_PASSWORD";
export type DBErrorCode = string;
export const DBErrCodeDuplicateRecord: DBErrorCode = "23505";
