// Code generated by tygo. DO NOT EDIT.
import * as uuid from "uuid"

//////////
// source: errors.go

export interface AppError {
  Code: AppErrorCode;
  Message: string;
  Payload: any;
}
export type AppErrorCode = string;
export const AppErrCodeUserWelcomeEmailNotSent: AppErrorCode = "USER_WELCOME_EMAIL_NOT_SENT";
export const AppErrorCodeUserNotAuthenticated: AppErrorCode = "USER_NOT_AUTHENTICATED";
export const AppErrorCodeRecordNotFound: AppErrorCode = "RECORD_NOT_FOUND";
export type DBErrorCode = string;
export const DBErrCodeDuplicateRecord: DBErrorCode = "23505";
