// Code generated by tygo. DO NOT EDIT.

//////////
// source: errors.go

export interface AppError {
  Code: AppErrorCode;
  Message: string;
  Payload: any;
}
export type AppErrorCode = string;
export const AppErrCodeUserWelcomeEmailNotSent: AppErrorCode = "USER_WELCOME_EMAIL_NOT_SENT";
export const AppErrorCodeUserNotAuthenticated: AppErrorCode = "USER_NOT_AUTHENTICATED";
export const AppErrorCodeRecordNotFound: AppErrorCode = "RECORD_NOT_FOUND";
export type DBErrorCode = string;
export const DBErrCodeDuplicateRecord: DBErrorCode = "23505";

//////////
// source: project.handler.go

export interface ProjectHandler {
}
export interface ProjectSampleCreatePayload {
  Project: uuid.UUIDTypes; // `form:"project"`
  Samples: ProjectSampleCreate[]; // `form:"samples"`
  DataFiles: { [key: uuid.UUIDTypes]: any /* multipart.FileHeader */}; // `form:datafiles`
}
export interface ProjectSampleCreate {
  Label: string;
  Tags: string[];
  Properties: any /* service.Property */[];
  Data: ProjectSampleDataCreate[];
  Notes: any /* service.ProjectSampleNoteCreate */[];
}
export interface ProjectSampleDataCreate {
  Schema: uuid.UUIDTypes;
  File: uuid.UUIDTypes;
  Timestamp: Date;
  Properties: any /* service.ProjectSampleDataPropertyCreate */[];
}
export interface Payload {
  project: uuid.UUIDTypes;
  update: any /* service.ProjectSampleUpdate */;
}
