// Code generated by tygo. DO NOT EDIT.
import * as uuid from "uuid";

//////////
// source: app.handler.go

export interface AppHandler {}
export const AppAccountNameKey = "app:account:name";
export const AppAccountLogoKey = "app:account:logo";
export const StaticFilePrefix = "public";

//////////
// source: data.handler.go

export interface DataHandler {}

//////////
// source: project.handler.go

export interface ProjectHandler {}
export interface ProjectSampleCreatePayload {
    Project: uuid.UUIDTypes;
    Samples: ProjectSampleCreate[];
}
export interface ProjectSampleCreate {
    Label: string;
    Tags: string[];
    Properties: any /* service.Property */[];
    Data: ProjectSampleDataCreate[];
    Notes: any /* service.ProjectSampleNoteCreate */[];
}
export interface ProjectSampleDataCreate {
    Schema: uuid.UUIDTypes;
    File: uuid.UUIDTypes;
    Timestamp: Date;
    Properties: any /* service.ProjectSampleDataPropertyCreate */[];
}
export interface Payload {
    project: uuid.UUIDTypes;
    update: any /* service.ProjectSampleUpdate */;
}

//////////
// source: user.handler.go

export const UserIdKey: string = "user_id";
export interface UserHandler {}
