// Code generated by tygo. DO NOT EDIT.
import * as uuid from "uuid"

//////////
// source: app.service.go

export interface FileFilter {
  DisplayName: string; // Filter information EG: "Image Files (*.jpg, *.png)"
  Pattern: string; // semicolon separated list of extensions, EG: "*.jpg;*.png"
}
export interface AppService {
}
export interface DbPermissionRecord {
  Id: string;
  Label: string;
  Description: string;
}
export const AppDataKeyEmailUrl = "app:email:url";
export const AppDataKeyEmailUsername = "app:email:username";
export const AppDataKeyEmailPassword = "app:email:password";
export const AppDataKeyEmailFrom = "app:email:from";
export const AppDataKeyAccountName = "app:account:name";
export const AppDataKeyAccountLogo = "app:account:logo";
export const AppDataKeyDataPath = "app:data:path";
export type AppDataKey = typeof AppDataKeyEmailUrl | typeof AppDataKeyEmailUsername | typeof AppDataKeyEmailPassword | typeof AppDataKeyEmailFrom | typeof AppDataKeyAccountName | typeof AppDataKeyAccountLogo | typeof AppDataKeyDataPath;
export const AppDataDirIngestionScript = "ingestion";
export const AppDataDirTransform = "transform";
export type AppDataDir = typeof AppDataDirIngestionScript | typeof AppDataDirTransform;

//////////
// source: common.go

export interface InsufficientPermissionsError {
}

//////////
// source: data.service.go

export const ValueTypeString = "string";
export const ValueTypeInt = "int";
export const ValueTypeUint = "uint";
export const ValueTypeFloat = "float";
export const ValueTypeBoolean = "boolean";
export const ValueTypeTimestamp = "timestamp";
export type ValueType = typeof ValueTypeString | typeof ValueTypeInt | typeof ValueTypeUint | typeof ValueTypeFloat | typeof ValueTypeBoolean | typeof ValueTypeTimestamp;
export const SaveDataHierarchyFlat = "flat";
export const SaveDataHierarchyDataSchema = "data_schema";
export const SaveDataHierarchySample = "sample";
export const SaveDataHierarchySampleDataSchema = "sample-data_scmeha";
export const SaveDataHierarchyDataSchemaSample = "data_schema-sample";
export type SaveDataHierarchy = typeof SaveDataHierarchyFlat | typeof SaveDataHierarchyDataSchema | typeof SaveDataHierarchySample | typeof SaveDataHierarchySampleDataSchema | typeof SaveDataHierarchyDataSchemaSample;
export interface DataService {
}
export const DataStorageInternal = "internal";
export const DataStorageExternal = "external";
export type DataStorage = typeof DataStorageInternal | typeof DataStorageExternal;
export const DataSourceCardinalitySingle = "single";
export const DataSourceCardinalityMultiple = "multiple";
export type DataSourceCardinality = typeof DataSourceCardinalitySingle | typeof DataSourceCardinalityMultiple;
export interface DataTypeInternalStorageRx {
  DataType: uuid.UUIDTypes;
  Schema: uuid.UUIDTypes;
}
export interface DataTypeExternalSourceRx {
  Id: uuid.UUIDTypes;
  DataType: uuid.UUIDTypes;
  Label: string;
  Required: boolean;
  Cardinality: DataSourceCardinality;
  Description: string;
  ExtFilter: string[];
}
export interface DataTypeRx {
  Id: uuid.UUIDTypes;
  Creator: uuid.UUIDTypes;
  Storage: DataStorage;
  Label: string;
  Description: string;
  Active: boolean;
}
export type DataType = any;
export interface DataTypeInternal {
  Id: uuid.UUIDTypes;
  Creator: uuid.UUIDTypes;
  Storage: DataStorage;
  Label: string;
  Description: string;
  Active: boolean;
  Schema: uuid.UUIDTypes;
}
export interface DataTypeExternal {
  Id: uuid.UUIDTypes;
  Creator: uuid.UUIDTypes;
  Storage: DataStorage;
  Label: string;
  Description: string;
  Active: boolean;
  Sources: DataTypeExternalSourceRx[];
}
export interface DataTypeSourceCreate {
  Cardinality: DataSourceCardinality;
  Required: boolean;
  ExtensionFilter: string[];
  Label: string;
  Description?: string;
}
export const FieldsPerRecord = 5;
export const RecordOffset = 1;
export interface DataTypeSourceUpdate {
  Id: uuid.UUIDTypes;
  Description: string;
  ExtensionFilter: string[];
}
export interface DataTypeUpdate {
  Id: uuid.UUIDTypes;
  Active: boolean;
  Label: string;
  Description: string;
  Sources: DataTypeSourceUpdate[];
}
export const DataSchemaCardinalitySingle = "single";
export const DataSchemaCardinalityMultiple = "multiple";
export type DataSchemaCardinality = typeof DataSchemaCardinalitySingle | typeof DataSchemaCardinalityMultiple;
export interface DataSchemaRx {
  Id: uuid.UUIDTypes;
  Creator: uuid.UUIDTypes;
  Cardinality: DataSchemaCardinality;
  Label: string;
  Description: string;
}
export interface DataSchemaFieldRx {
  Id: uuid.UUIDTypes;
  Label: string;
  DType: ValueType;
  Description: string;
}
export interface DataSchemaField {
  Label: string;
  DType: ValueType;
  Description: string;
}
export interface DataSchema {
  Id: uuid.UUIDTypes;
  Creator: uuid.UUIDTypes;
  Cardinality: DataSchemaCardinality;
  Label: string;
  Description: string;
  Schema: DataSchemaField[];
}
export interface InvalidSampleDataColumnLabels {
  Labels: string[];
}
export const PATTERN = `^[\\w_]+\$`;
export interface DataSchemaCreate {
  Cardinality: DataSchemaCardinality;
  Schema: DataSchemaField[];
  Label: string;
  Description: string;
}
export const NumFields = 3;
export const ArgsOffset = 1;
export const TABLE_NAME_PREFIX = "data_schema";
export interface DataSchemaUpdate {
  Id: uuid.UUIDTypes;
  Label: string;
  Description?: string;
}
export interface DataSchemaResources {
  DataSchema: DataSchema;
  Creator: User;
}
export interface InvalidFileExtensionError {
}
export interface IncompatibleDataSizeError {
}
export interface ColumnData {
  Label: string;
  DType: ValueType;
  Values: any[];
}
export interface ParseCsvError {
  Record: number /* uint */;
  Column: number /* int */;
  Err: error;
}
export interface InvalidDataTypeError {
  Value: string;
  DType: ValueType;
}
export interface IngestionScriptRx {
  Id: uuid.UUIDTypes;
  Type: uuid.UUIDTypes;
  Creator: uuid.UUIDTypes;
  Cmd: uuid.UUIDTypes;
  Label: string;
  Description: string;
}
export interface IngestionScriptCmdRx {
  Id: uuid.UUIDTypes;
  Creator: uuid.UUIDTypes;
  Path: string;
  Cmd: string;
  Args: string[];
}
export interface IngestionScript {
  Id: uuid.UUIDTypes;
  Type: uuid.UUIDTypes;
  Creator: uuid.UUIDTypes;
  Label: string;
  Description: string;
  Cmd: IngestionScriptCmdRx;
}
export interface IngestionScriptCreate {
  Type: uuid.UUIDTypes;
  Creator: uuid.UUIDTypes;
  Label: string;
  Description: string;
  Path: string;
  Cmd: string;
  Args: string[];
}
/**
 * StoredData represents the actual data stored.
 * Data is []SchemaField if Storage is `internal`.
 * Data is a path (`string`) if Storage is `external`.
 */
export interface StoredData {
  SampleData: uuid.UUIDTypes;
  Storage: DataStorage;
  Data: any;
}
export interface SampleDataSchema {
  SampleData: uuid.UUIDTypes;
  DataSchema: uuid.UUIDTypes;
}
export interface DataSchemaRx {
  Id: uuid.UUIDTypes;
  Schema: DataSchemaField[];
}
export interface SampleDataInfo {
  SampleData: uuid.UUIDTypes;
  Sample: uuid.UUIDTypes;
  DataSchema: uuid.UUIDTypes;
  Timestamp: Date;
}
export interface SampleInfo {
  Id: uuid.UUIDTypes;
  Label: string;
}
export interface DataSchemaRx {
  Id: uuid.UUIDTypes;
  Label: string;
}
export interface SampleRx {
  Sample: uuid.UUIDTypes;
  SampleData: uuid.UUIDTypes;
  Label: string;
  Timestamp: Date;
}
export interface ProjectSampleRx {
  Sample: uuid.UUIDTypes;
  Label: string;
}
export interface SampleDataRx {
  Id: uuid.UUIDTypes;
  Sample: uuid.UUIDTypes;
  DataSchema: uuid.UUIDTypes;
  Timestamp: Date;
}
export interface DataSchemaRx {
  Id: uuid.UUIDTypes;
  Label: string;
}
export const SampleDataUserPermissionOwner = "owner";
export const SampleDataUserPermissionRead = "read";
export const SampleDataUserPermissionCreateNote = "create_note";
export const SampleDataUserPermissionModifyProperties = "modify_properties";
export type SampleDataUserPermission = typeof SampleDataUserPermissionOwner | typeof SampleDataUserPermissionRead | typeof SampleDataUserPermissionCreateNote | typeof SampleDataUserPermissionModifyProperties;
export interface SampleDataUserPermissions {
  SampleData: uuid.UUIDTypes;
  Permissions: SampleDataUserPermission[];
}
export interface DataTypeTransformRx {
  Id: uuid.UUIDTypes;
  Source: uuid.UUIDTypes;
  Destination: uuid.UUIDTypes;
  Script: string;
  Creator: User;
  Label: string;
  Description: string;
}
export interface DataTypeTransformCreate {
  Source: uuid.UUIDTypes;
  Destination: uuid.UUIDTypes;
  Script?: any /* multipart.FileHeader */;
  Label: string;
  Description: string;
}

//////////
// source: project.service.go

export const ProjectPermissionOwner = "owner";
export const ProjectPermissionCreateSample = "create_sample";
export const ProjectPermissionRead = "read";
export type ProjectPermission = typeof ProjectPermissionOwner | typeof ProjectPermissionCreateSample | typeof ProjectPermissionRead;
export const ProjectSamplePermissionModifyLabel = "modify_label";
export const ProjectSamplePermissionModifyTags = "modify_tags";
export const ProjectSamplePermissionModifyProperties = "modify_properties";
export type ProjectSamplePermission = typeof ProjectSamplePermissionModifyLabel | typeof ProjectSamplePermissionModifyTags | typeof ProjectSamplePermissionModifyProperties;
export const VisibilityPublic = "public";
export const VisibilityPrivate = "private";
export type Visibility = typeof VisibilityPublic | typeof VisibilityPrivate;
export interface ProjectService {
}
export interface Project {
  Id: uuid.UUIDTypes;
  Creator: uuid.UUIDTypes;
  Label: string;
  Description: string;
  Visibility: Visibility;
}
export interface ProjectCreate {
  Label: string;
  Description: string;
  Visibility: Visibility;
}
export const PropertyTypeString = "string";
export const PropertyTypeBool = "bool";
export const PropertyTypeUint = "uint";
export const PropertyTypeInt = "int";
export const PropertyTypeFloat = "float";
export const PropertyTypeQuantity = "quantity";
export const PropertyTypeTimestamp = "timestamp";
export type PropertyType = typeof PropertyTypeString | typeof PropertyTypeBool | typeof PropertyTypeUint | typeof PropertyTypeInt | typeof PropertyTypeFloat | typeof PropertyTypeQuantity | typeof PropertyTypeTimestamp;
export interface Property {
  Key: string;
  Type: PropertyType;
  Value: any; // TODO: Match value with type
}
export interface ProjectSampleNote {
  Id: uuid.UUIDTypes;
  Sample: uuid.UUIDTypes;
  Project: uuid.UUIDTypes;
  Creator: uuid.UUIDTypes;
  Timestamp: Date;
  Content: string;
}
export interface ProjectSample {
  Id: uuid.UUIDTypes;
  Creator: uuid.UUIDTypes;
  MembershipCreator: uuid.UUIDTypes;
  MembershipCreated: Date;
  Label: string;
  Tags: string[];
  Properties: Property[];
  NoteCount: number /* uint */;
}
export interface DataRecord {
  Id: uuid.UUIDTypes;
  Creator: uuid.UUIDTypes;
  Type: uuid.UUIDTypes;
  Timestamp: Date;
  Visibility: Visibility;
}
export interface DerivedData {
  Parent: uuid.UUIDTypes;
  Transform: uuid.UUIDTypes;
  SampleData: uuid.UUIDTypes;
  Schema: uuid.UUIDTypes;
}
export interface ProjectSampleGroup {
  Id: uuid.UUIDTypes;
  Creator: uuid.UUIDTypes;
  Label: string;
  Description: string;
  Properties: Property[];
  Samples: uuid.UUIDTypes[];
}
export interface SampleGroupRelation {
  Parent: uuid.UUIDTypes;
  Child: uuid.UUIDTypes;
}
export interface ProjectResources {
  Project: Project;
  ProjectTags: string[];
  Samples: ProjectSample[];
  RawData: DataRecord[];
  DataSchemas: DataSchema[];
  SampleGroups: ProjectSampleGroup[];
  SampleGroupRelations: SampleGroupRelation[];
  ProjectNoteCount: number /* uint */;
  ProjectPermissions: ProjectPermission[];
}
export interface ProjectSampleInfo {
  Id: uuid.UUIDTypes;
  Tags: string[];
  Properties: Property[];
  NoteCount: number /* uint */;
}
export interface ProjectWithUserPermission {
  Id: uuid.UUIDTypes;
  Creator: uuid.UUIDTypes;
  Label: string;
  Description: string;
  Visibility: Visibility;
  Permissions: ProjectPermission[];
}
export interface FileInfo {
  Name: string;
  Size: number /* int64 */;
  File?: File;
}
export interface ProjectSampleDataCreate {
  Schema: uuid.UUIDTypes;
  File: FileInfo;
  Timestamp: Date;
  Properties: ProjectSampleDataPropertyCreate[];
}
export interface ProjectSampleDataPropertyCreate {
  Key: string;
  Type: PropertyType;
  Value: any; // TODO: match type
}
export interface SampleDataPayloadExternal {
  Path: string;
  Filename: string;
}
export interface ProjectSampleNoteCreate {
  Timestamp: Date;
  Content: string;
}
export interface ProjectSampleCreate {
  Label: string;
  Tags: string[];
  Properties: Property[];
  Data: ProjectSampleDataCreate[];
  Notes: ProjectSampleNoteCreate[];
}
export const NUM_PROPERTY_VALUES = 3;
export const NUM_VALUES_PER_PROPERTY = 4;
export const NUM_NOTE_VALUES = 2;
export const PROJECT_SAMPLE_USER_PERMISSION_COUNT = 3;
export interface ParseSampleDataErrors {
}
export interface ProjectSampleMembershipAsResource {
  Creator: User;
  Timestamp: Date;
  Label: string;
}
export interface SampleUserPermissions {
  User: uuid.UUIDTypes;
  Permissions: SampleUserPermission[];
}
export interface ProjectSampleUserPermissions {
  User: uuid.UUIDTypes;
  Permissions: ProjectSamplePermission[];
}
export interface ProjectSampleResources {
  Id: uuid.UUIDTypes;
  Creator: uuid.UUIDTypes;
  Properties: Property[];
  ProjectMembership: ProjectSampleMembershipAsResource;
  ProjectTags: string[];
  ProjectNotes: ProjectSampleNote[];
  RawData: DataRecord[];
  DerivedData: DerivedData[];
  DataSchemas: DataSchema[];
  Users: User[];
  SampleUserPermissions: SampleUserPermissions[];
  ProjectSampleUserPermissions: ProjectSampleUserPermissions[];
}
export interface ProjectSampleNoteUpdate {
  Id: uuid.UUIDTypes;
  Editor: uuid.UUIDTypes;
  Content: string;
}
export interface ProjectSampleUpdate {
  Id: uuid.UUIDTypes;
  Label: string;
  Tags: string[];
  PropertiesUpsert: Property[];
  PropertiesRemove: string[];
  NotesNew: ProjectSampleNoteCreate[];
  NotesUpdate: ProjectSampleNoteUpdate[];
  NotesRemove: uuid.UUIDTypes[];
}
export interface ProjectSampleMembership {
  Project: uuid.UUIDTypes;
  Sample: uuid.UUIDTypes;
  Creator: uuid.UUIDTypes;
  Timestamp: Date;
  Label: string;
}

//////////
// source: sample.service.go

export const SampleUserPermissionOwner = "owner";
export const SampleUserPermissionRead = "read";
export const SampleUserPermissionAddData = "add_data";
export const SampleUserPermissionCreateNote = "create_note";
export const SampleUserPermissionModifyProperties = "modify_properties";
export type SampleUserPermission = typeof SampleUserPermissionOwner | typeof SampleUserPermissionRead | typeof SampleUserPermissionAddData | typeof SampleUserPermissionCreateNote | typeof SampleUserPermissionModifyProperties;
export interface SampleService {
}

//////////
// source: user.service.go

export const AppEmailUrlKey = "app:email:url";
export const AppEmailUsernameKey = "app:email:username";
export const AppEmailPasswordKey = "app:email:password";
export const AppEmailFromKey = "app:email:from";
export const DbPermissionIdOwner = "owner";
export const DbPermissionIdUserCreate = "user_create";
export const DbPermissionIdUserModify = "user_modify";
export const DbPermissionIdDataSchemaCreate = "data_schema_create";
export const DbPermissionIdDataSchemaModify = "data_schema_modify";
export const DbPermissionIdDataTypeCreate = "data_type_create";
export const DbPermissionIdDataTypeModify = "data_type_modify";
export const DbPermissionIdIngestionScriptCreate = "ingestion_script_create";
export const DbPermissionIdIngestionScriptModify = "ingestion_script_modify";
export const DbPermissionIdTransformCreate = "transform_create";
export const DbPermissionIdTransformModify = "transform_modify";
export const DbPermissionIdProjectCreate = "project_create";
export type DbPermissionId = typeof DbPermissionIdOwner | typeof DbPermissionIdUserCreate | typeof DbPermissionIdUserModify | typeof DbPermissionIdDataSchemaCreate | typeof DbPermissionIdDataSchemaModify | typeof DbPermissionIdDataTypeCreate | typeof DbPermissionIdDataTypeModify | typeof DbPermissionIdIngestionScriptCreate | typeof DbPermissionIdIngestionScriptModify | typeof DbPermissionIdTransformCreate | typeof DbPermissionIdTransformModify | typeof DbPermissionIdProjectCreate;
export const AccountStatusActive = "active";
export const AccountStatusDeactivated = "deactivated";
export type AccountStatus = typeof AccountStatusActive | typeof AccountStatusDeactivated;
export interface UserService {
}
export interface UserRecord {
  Id: uuid.UUIDTypes;
  AccountStatus: AccountStatus;
  Email: string;
  Name: string;
}
export interface User {
  Id: uuid.UUIDTypes;
  AccountStatus: AccountStatus;
  Email: string;
  Name: string;
  DbPermissions: DbPermissionId[];
}
export interface UserCreate {
  Email: string;
  Name: string;
  Password: string;
  DbPermissions: DbPermissionId[];
}
