// Code generated by tygo. DO NOT EDIT.
import * as uuid from "uuid"

//////////
// source: app.service.go

export interface FileFilter {
  DisplayName: string; // Filter information EG: "Image Files (*.jpg, *.png)"
  Pattern: string; // semicolon separated list of extensions, EG: "*.jpg;*.png"
}
export interface AppService {
}
export interface DbPermissionRecord {
  Id: string;
  Label: string;
  Description: string;
}
export const AppDataKeyEmailUrl = "app:email:url";
export const AppDataKeyEmailUsername = "app:email:username";
export const AppDataKeyEmailPassword = "app:email:password";
export const AppDataKeyEmailFrom = "app:email:from";
export const AppDataKeyAccountName = "app:account:name";
export const AppDataKeyAccountLogo = "app:account:logo";
export const AppDataKeyDataPath = "app:data:path";
export type AppDataKey = typeof AppDataKeyEmailUrl | typeof AppDataKeyEmailUsername | typeof AppDataKeyEmailPassword | typeof AppDataKeyEmailFrom | typeof AppDataKeyAccountName | typeof AppDataKeyAccountLogo | typeof AppDataKeyDataPath;
export const AppDataDirIngestionScript = "ingestion";
export const AppDataDirIngestionScriptSource = "ingestion_source";
export const AppDataDirTransform = "transform";
export type AppDataDir = typeof AppDataDirIngestionScript | typeof AppDataDirIngestionScriptSource | typeof AppDataDirTransform;

//////////
// source: common.go

export interface InsufficientPermissionsError {
}

//////////
// source: data.service.go

export const ValueTypeString = "string";
export const ValueTypeInt = "int";
export const ValueTypeUint = "uint";
export const ValueTypeFloat = "float";
export const ValueTypeBoolean = "boolean";
export const ValueTypeTimestamp = "timestamp";
export type ValueType = typeof ValueTypeString | typeof ValueTypeInt | typeof ValueTypeUint | typeof ValueTypeFloat | typeof ValueTypeBoolean | typeof ValueTypeTimestamp;
export const SaveDataHierarchyFlat = "flat";
export const SaveDataHierarchyDataSchema = "data_schema";
export const SaveDataHierarchySample = "sample";
export const SaveDataHierarchySampleDataSchema = "sample-data_scmeha";
export const SaveDataHierarchyDataSchemaSample = "data_schema-sample";
export type SaveDataHierarchy = typeof SaveDataHierarchyFlat | typeof SaveDataHierarchyDataSchema | typeof SaveDataHierarchySample | typeof SaveDataHierarchySampleDataSchema | typeof SaveDataHierarchyDataSchemaSample;
export interface DataService {
}
export const DataStorageInternal = "internal";
export const DataStorageExternal = "external";
export type DataStorage = typeof DataStorageInternal | typeof DataStorageExternal;
export const DataSourceCardinalitySingle = "single";
export const DataSourceCardinalityMultiple = "multiple";
export type DataSourceCardinality = typeof DataSourceCardinalitySingle | typeof DataSourceCardinalityMultiple;
export interface DataTypeInternalStorageRx {
  DataType: uuid.UUIDTypes;
  Schema: uuid.UUIDTypes;
}
export interface DataTypeExternalSourceRx {
  Id: uuid.UUIDTypes;
  DataType: uuid.UUIDTypes;
  Label: string;
  Required: boolean;
  Cardinality: DataSourceCardinality;
  Description: string;
  ExtFilter: string[];
}
export interface DataTypeRx {
  Id: uuid.UUIDTypes;
  Creator: uuid.UUIDTypes;
  Storage: DataStorage;
  Label: string;
  Description: string;
  Active: boolean;
}
export type DataType = any;
export interface DataTypeInternal {
  Id: uuid.UUIDTypes;
  Creator: uuid.UUIDTypes;
  Storage: DataStorage;
  Label: string;
  Description: string;
  Active: boolean;
  Schema: uuid.UUIDTypes;
}
export interface DataTypeExternal {
  Id: uuid.UUIDTypes;
  Creator: uuid.UUIDTypes;
  Storage: DataStorage;
  Label: string;
  Description: string;
  Active: boolean;
  Sources: DataTypeExternalSourceRx[];
}
export type DataCreator = any;
export interface DataCreatorUser {
  Id: uuid.UUIDTypes;
  Origin: uuid.UUIDTypes;
}
export interface DataCreatorTransform {
  Id: uuid.UUIDTypes;
}
export interface ExternalSourceCreate {
  Cardinality: DataSourceCardinality;
  Required: boolean;
  ExtensionFilter: string[];
  Label: string;
  Description?: string;
}
export interface DataTypeSourceUpdate {
  Id: uuid.UUIDTypes;
  Description: string;
  ExtensionFilter: string[];
}
export interface DataTypeUpdate {
  Id: uuid.UUIDTypes;
  Active: boolean;
  Label: string;
  Description: string;
  Sources: DataTypeSourceUpdate[];
}
export const DataSchemaCardinalitySingle = "single";
export const DataSchemaCardinalityMultiple = "multiple";
export type DataSchemaCardinality = typeof DataSchemaCardinalitySingle | typeof DataSchemaCardinalityMultiple;
export interface DataSchemaRx {
  Id: uuid.UUIDTypes;
  Creator: uuid.UUIDTypes;
  Cardinality: DataSchemaCardinality;
  Label: string;
  Description: string;
}
export interface DataSchemaFieldRx {
  Id: uuid.UUIDTypes;
  Label: string;
  DType: ValueType;
  Required: boolean;
  Nullable: boolean;
  Index: number /* uint */;
  Description: string;
}
export interface DataSchemaField {
  Label: string;
  DType: ValueType;
  Required: boolean;
  Nullable: boolean;
  Index: number /* uint */;
  Description: string;
}
export interface DataSchema {
  Id: uuid.UUIDTypes;
  Creator: uuid.UUIDTypes;
  Cardinality: DataSchemaCardinality;
  Label: string;
  Description: string;
  Fields: DataSchemaField[];
}
export interface InvalidSampleDataColumnLabels {
  Labels: string[];
}
export interface DataSchemaCreate {
  Cardinality: DataSchemaCardinality;
  Schema: DataSchemaField[];
  Label: string;
  Description: string;
}
export interface DataSchemaUpdate {
  Id: uuid.UUIDTypes;
  Label: string;
  Description?: string;
}
export interface DataSchemaResources {
  DataSchema: DataSchema;
  Creator: User;
}
export interface InvalidFileExtensionError {
}
export interface IncompatibleDataSizeError {
}
/**
 * Values a single `DType` if Cardinality is `single`,
 * a slice of `DType` if Cardinality is `multiple`.
 */
export interface SchemaFieldValues {
  Label: string;
  DType: ValueType;
  Cardinality: DataSchemaCardinality;
  Values: any;
}
export interface ParseCsvError {
  Record: number /* uint */;
  Column: number /* int */;
  Err: error;
}
export interface InvalidDataTypeError {
  Value: string;
  DType: ValueType;
}
export interface IngestionScriptRx {
  Id: uuid.UUIDTypes;
  Type: uuid.UUIDTypes;
  Creator: uuid.UUIDTypes;
  Cmd: uuid.UUIDTypes;
  Label: string;
  Description: string;
}
export interface IngestionScriptCmdRx {
  Id: uuid.UUIDTypes;
  Creator: uuid.UUIDTypes;
  Path: string;
  Cmd: string;
  Args: string[];
}
export interface IngestionScriptSourceRx {
  Id: uuid.UUIDTypes;
  Script: uuid.UUIDTypes;
  Label: string;
  Required: boolean;
  Cardinality: DataSourceCardinality;
  Description: string;
  ExtFilter: string[];
}
export interface IngestionScript {
  Id: uuid.UUIDTypes;
  Type: uuid.UUIDTypes;
  Creator: uuid.UUIDTypes;
  Label: string;
  Description: string;
  Cmd: IngestionScriptCmdRx;
  Sources: IngestionScriptSourceRx[];
}
export interface IngestionScriptCreate {
  Type: uuid.UUIDTypes;
  Creator: uuid.UUIDTypes;
  Label: string;
  Description: string;
  Path: string;
  Cmd: string;
  Args: string[];
  Sources: ExternalSourceCreate[];
}
export interface DataOriginRx {
  Id: uuid.UUIDTypes;
  Label: string;
  Description: string;
  Active: boolean;
}
/**
 * DataValues represents the actual data stored.
 * Values is []SchemaFieldValues if Storage is `internal`.
 * Values is a []DataSource if Storage is `external`.
 */
export interface DataValues {
  Data: uuid.UUIDTypes;
  Storage: DataStorage;
  Values: any;
}
/**
 * DataSource is an externally stored data source.
 * `Sources` is a single path if `Cardinality` is `single`.
 * `Sources` is an array of paths if `Cardinality` is `multiple`.
 */
export interface DataSource {
  Label: string;
  Cardinality: DataSourceCardinality;
  Source: any;
}
export const DataUserPermissionOwner = "owner";
export const DataUserPermissionRead = "read";
export const DataUserPermissionNoteCreate = "note_create";
export const DataUserPermissionPropertiesModify = "properties_modify";
export type DataUserPermission = typeof DataUserPermissionOwner | typeof DataUserPermissionRead | typeof DataUserPermissionNoteCreate | typeof DataUserPermissionPropertiesModify;
export interface DataUserPermissions {
  Data: uuid.UUIDTypes;
  Permissions: DataUserPermission[];
}
export interface DataTypeTransformRx {
  Id: uuid.UUIDTypes;
  Creator: uuid.UUIDTypes;
  Source: uuid.UUIDTypes;
  Destination: uuid.UUIDTypes;
  Cmd: uuid.UUIDTypes;
  Label: string;
  Description: string;
}
export interface DataTypeTransformCmdRx {
  Id: uuid.UUIDTypes;
  Creator: uuid.UUIDTypes;
  Path: string;
  Cmd: string;
  Args: string[];
}
export interface DataTypeTransform {
  Id: uuid.UUIDTypes;
  Creator: uuid.UUIDTypes;
  Source: uuid.UUIDTypes;
  Destination: uuid.UUIDTypes;
  Label: string;
  Description: string;
  Cmd: DataTypeTransformCmdRx;
}
export interface DataTypeTransformCreate {
  Creator: uuid.UUIDTypes;
  Source: uuid.UUIDTypes;
  Destination: uuid.UUIDTypes;
  Label: string;
  Description: string;
  Cmd: string;
  Args: string[];
  Script?: any /* multipart.FileHeader */;
}
export const DataCreatorTypeUser = "user";
export const DataCreatorTypeTransform = "transform";
export type DataCreatorType = typeof DataCreatorTypeUser | typeof DataCreatorTypeTransform;
export interface Note {
  Timestamp: Date;
  Visibility: Visibility;
  Content: string;
}
export type DataIngestionMethod = string;
export const DataIngestionManual: DataIngestionMethod = "manual";
export const DataIngestionScript: DataIngestionMethod = "script";
/**
 * `Values` is only valid if `IngestionMethod` is `manual`.
 * `IngestionScript` and `IngestionScriptSources` are only valid if `IngestionMethod` is `script`.
 */
export interface DataCreate {
  Type: uuid.UUIDTypes;
  Creator: DataCreatorUser;
  Timestamp: Date;
  Visibility: Visibility;
  Properties: Property[];
  Notes: Note[];
  IngestionMethod: DataIngestionMethod;
  Values: { [key: string]: any};
  IngestionScript: uuid.UUIDTypes;
  IngestionScriptSources: { [key: uuid.UUIDTypes]: (any /* multipart.FileHeader */ | undefined)[]};
}
export const DataPermissionKeyOwner = "owner";
export const DataPermissionKeyRead = "read";
export const DataPermissionKeyNoteCreate = "note_create";
export const DataPermissionKeyPropertiesModify = "properties_modify";
export type DataPermissionKey = typeof DataPermissionKeyOwner | typeof DataPermissionKeyRead | typeof DataPermissionKeyNoteCreate | typeof DataPermissionKeyPropertiesModify;
export const FIELDS = 3;
export interface DataWithOrigin {
  Data: DataRx;
  Origin: uuid.UUIDTypes;
}
export interface OrphanedDataResources {
  Data: DataWithOrigin[];
  Origins: DataOriginRx[];
  DataTypes: DataType[];
}

//////////
// source: project.service.go

export const ProjectPermissionOwner = "owner";
export const ProjectPermissionRead = "read";
export const ProjectPermissionDataCreate = "data_create";
export const ProjectPermissionDataGroupCreate = "data_group_create";
export type ProjectPermission = typeof ProjectPermissionOwner | typeof ProjectPermissionRead | typeof ProjectPermissionDataCreate | typeof ProjectPermissionDataGroupCreate;
export const ProjectSamplePermissionModifyLabel = "modify_label";
export const ProjectSamplePermissionModifyTags = "modify_tags";
export const ProjectSamplePermissionModifyProperties = "modify_properties";
export type ProjectSamplePermission = typeof ProjectSamplePermissionModifyLabel | typeof ProjectSamplePermissionModifyTags | typeof ProjectSamplePermissionModifyProperties;
export const VisibilityPublic = "public";
export const VisibilityPrivate = "private";
export type Visibility = typeof VisibilityPublic | typeof VisibilityPrivate;
export interface ProjectService {
}
export interface Project {
  Id: uuid.UUIDTypes;
  Creator: uuid.UUIDTypes;
  Label: string;
  Description: string;
  Visibility: Visibility;
}
export interface ProjectCreate {
  Label: string;
  Description: string;
  Visibility: Visibility;
}
export const PropertyTypeString = "string";
export const PropertyTypeBool = "bool";
export const PropertyTypeUint = "uint";
export const PropertyTypeInt = "int";
export const PropertyTypeFloat = "float";
export const PropertyTypeQuantity = "quantity";
export const PropertyTypeTimestamp = "timestamp";
export type PropertyType = typeof PropertyTypeString | typeof PropertyTypeBool | typeof PropertyTypeUint | typeof PropertyTypeInt | typeof PropertyTypeFloat | typeof PropertyTypeQuantity | typeof PropertyTypeTimestamp;
export interface Property {
  Key: string;
  Type: PropertyType;
  Value: any; // TODO: Match value with type
}
export interface ProjectSampleNote {
  Id: uuid.UUIDTypes;
  Sample: uuid.UUIDTypes;
  Project: uuid.UUIDTypes;
  Creator: uuid.UUIDTypes;
  Timestamp: Date;
  Content: string;
}
export interface ProjectData {
  Id: uuid.UUIDTypes;
  Type: uuid.UUIDTypes;
  Creator: DataCreator;
  MembershipCreator: uuid.UUIDTypes;
  Timestamp: Date;
  Label?: string;
  Tags: string[];
  Properties: Property[];
  NoteCount: number /* uint */;
}
export interface DataRx {
  Id: uuid.UUIDTypes;
  Type: uuid.UUIDTypes;
  CreatorType: DataCreatorType;
  Timestamp: Date;
  Visibility: Visibility;
}
export interface DerivedData {
  Parent: uuid.UUIDTypes;
  Transform: uuid.UUIDTypes;
  SampleData: uuid.UUIDTypes;
  Schema: uuid.UUIDTypes;
}
export interface ProjectDataGroup {
  Id: uuid.UUIDTypes;
  Creator: uuid.UUIDTypes;
  Label: string;
  Description: string;
  Properties: Property[];
  Samples: uuid.UUIDTypes[];
}
export interface DataGroupRelation {
  Parent: uuid.UUIDTypes;
  Child: uuid.UUIDTypes;
}
export interface ProjectResources {
  Project: Project;
  Tags: string[];
  Data: ProjectData[];
  DataTypes: DataType[];
  DataSchemas: DataSchema[];
  DataGroups: ProjectDataGroup[];
  DataGroupRelations: DataGroupRelation[];
  ProjectNoteCount: number /* uint */;
  ProjectPermissions: ProjectPermission[];
}
export interface ProjectDataInfo {
  Id: uuid.UUIDTypes;
  Type: uuid.UUIDTypes;
  Creator: DataCreator;
  Timestamp: Date;
  Tags: string[];
  Properties: Property[];
  NoteCount: number /* uint */;
}
export interface ProjectWithUserPermission {
  Id: uuid.UUIDTypes;
  Creator: uuid.UUIDTypes;
  Label: string;
  Description: string;
  Visibility: Visibility;
  Permissions: ProjectPermission[];
}
export interface FileInfo {
  Name: string;
  Size: number /* int64 */;
  File?: File;
}
export interface ProjectSampleDataCreate {
  Schema: uuid.UUIDTypes;
  File: FileInfo;
  Timestamp: Date;
  Properties: ProjectSampleDataPropertyCreate[];
}
export interface ProjectSampleDataPropertyCreate {
  Key: string;
  Type: PropertyType;
  Value: any; // TODO: match type
}
export interface SampleDataPayloadExternal {
  Path: string;
  Filename: string;
}
export interface ProjectSampleNoteCreate {
  Timestamp: Date;
  Content: string;
}
export interface ProjectSampleCreate {
  Label: string;
  Tags: string[];
  Properties: Property[];
  Data: ProjectSampleDataCreate[];
  Notes: ProjectSampleNoteCreate[];
}
export const NUM_PROPERTY_VALUES = 3;
export const NUM_VALUES_PER_PROPERTY = 4;
export const NUM_NOTE_VALUES = 2;
export const PROJECT_SAMPLE_USER_PERMISSION_COUNT = 3;
export interface ParseSampleDataErrors {
}
export interface ProjectSampleMembershipAsResource {
  Creator: User;
  Timestamp: Date;
  Label: string;
}
export interface SampleUserPermissions {
  User: uuid.UUIDTypes;
  Permissions: SampleUserPermission[];
}
export interface ProjectSampleUserPermissions {
  User: uuid.UUIDTypes;
  Permissions: ProjectSamplePermission[];
}
export interface ProjectSampleResources {
  Id: uuid.UUIDTypes;
  Creator: uuid.UUIDTypes;
  Properties: Property[];
  ProjectMembership: ProjectSampleMembershipAsResource;
  ProjectTags: string[];
  ProjectNotes: ProjectSampleNote[];
  Data: DataRx[];
  DerivedData: DerivedData[];
  DataSchemas: DataSchema[];
  Users: User[];
  SampleUserPermissions: SampleUserPermissions[];
  ProjectSampleUserPermissions: ProjectSampleUserPermissions[];
}
export interface ProjectSampleNoteUpdate {
  Id: uuid.UUIDTypes;
  Editor: uuid.UUIDTypes;
  Content: string;
}
export interface ProjectSampleUpdate {
  Id: uuid.UUIDTypes;
  Label: string;
  Tags: string[];
  PropertiesUpsert: Property[];
  PropertiesRemove: string[];
  NotesNew: ProjectSampleNoteCreate[];
  NotesUpdate: ProjectSampleNoteUpdate[];
  NotesRemove: uuid.UUIDTypes[];
}
export interface ProjectSampleMembership {
  Project: uuid.UUIDTypes;
  Sample: uuid.UUIDTypes;
  Creator: uuid.UUIDTypes;
  Timestamp: Date;
  Label: string;
}
export interface ProjectDataMembershipRx {
  Project: uuid.UUIDTypes;
  Data: uuid.UUIDTypes;
  Creator: uuid.UUIDTypes;
  Label?: string;
}

//////////
// source: sample.service.go

export const SampleUserPermissionOwner = "owner";
export const SampleUserPermissionRead = "read";
export const SampleUserPermissionAddData = "add_data";
export const SampleUserPermissionCreateNote = "create_note";
export const SampleUserPermissionModifyProperties = "modify_properties";
export type SampleUserPermission = typeof SampleUserPermissionOwner | typeof SampleUserPermissionRead | typeof SampleUserPermissionAddData | typeof SampleUserPermissionCreateNote | typeof SampleUserPermissionModifyProperties;
export interface SampleService {
}

//////////
// source: user.service.go

export const AppEmailUrlKey = "app:email:url";
export const AppEmailUsernameKey = "app:email:username";
export const AppEmailPasswordKey = "app:email:password";
export const AppEmailFromKey = "app:email:from";
export const DbPermissionOwner = "owner";
export const DbPermissionUserCreate = "user_create";
export const DbPermissionUserModify = "user_modify";
export const DbPermissionDataSchemaCreate = "data_schema_create";
export const DbPermissionDataSchemaModify = "data_schema_modify";
export const DbPermissionDataTypeCreate = "data_type_create";
export const DbPermissionDataTypeModify = "data_type_modify";
export const DbPermissionIngestionScriptCreate = "ingestion_script_create";
export const DbPermissionIngestionScriptModify = "ingestion_script_modify";
export const DbPermissionTransformCreate = "transform_create";
export const DbPermissionTransformModify = "transform_modify";
export const DbPermissionProjectCreate = "project_create";
export const DbPermissionDataCreate = "data_create";
export type DbPermission = typeof DbPermissionOwner | typeof DbPermissionUserCreate | typeof DbPermissionUserModify | typeof DbPermissionDataSchemaCreate | typeof DbPermissionDataSchemaModify | typeof DbPermissionDataTypeCreate | typeof DbPermissionDataTypeModify | typeof DbPermissionIngestionScriptCreate | typeof DbPermissionIngestionScriptModify | typeof DbPermissionTransformCreate | typeof DbPermissionTransformModify | typeof DbPermissionProjectCreate | typeof DbPermissionDataCreate;
export const AccountStatusActive = "active";
export const AccountStatusDeactivated = "deactivated";
export type AccountStatus = typeof AccountStatusActive | typeof AccountStatusDeactivated;
export interface UserService {
}
export interface UserRecord {
  Id: uuid.UUIDTypes;
  AccountStatus: AccountStatus;
  Email: string;
  Name: string;
}
export interface User {
  Id: uuid.UUIDTypes;
  AccountStatus: AccountStatus;
  Email: string;
  Name: string;
  DbPermissions: DbPermission[];
}
export interface UserCreate {
  Email: string;
  Name: string;
  Password: string;
  DbPermissions: DbPermission[];
}
