// Code generated by tygo. DO NOT EDIT.
import * as uuid from "uuid"

//////////
// source: app.service.go

export interface FileFilter {
  DisplayName: string; // Filter information EG: "Image Files (*.jpg, *.png)"
  Pattern: string; // semicolon separated list of extensions, EG: "*.jpg;*.png"
}
export interface AppService {
}

//////////
// source: common.go

export interface InsufficientPermissionsError {
}

//////////
// source: data.service.go

export const AppDataPath = "app:data:path";
export const AppTransformDir = "transforms";
export const DataTypeString = "string";
export const DataTypeInt = "int";
export const DataTypeUint = "uint";
export const DataTypeFloat = "float";
export const DataTypeBoolean = "boolean";
export const DataTypeTimestamp = "timestamp";
export type DataType = typeof DataTypeString | typeof DataTypeInt | typeof DataTypeUint | typeof DataTypeFloat | typeof DataTypeBoolean | typeof DataTypeTimestamp;
export const SaveDataHierarchyFlat = "flat";
export const SaveDataHierarchyDataSchema = "data_schema";
export const SaveDataHierarchySample = "sample";
export const SaveDataHierarchySampleDataSchema = "sample-data_scmeha";
export const SaveDataHierarchyDataSchemaSample = "data_schema-sample";
export type SaveDataHierarchy = typeof SaveDataHierarchyFlat | typeof SaveDataHierarchyDataSchema | typeof SaveDataHierarchySample | typeof SaveDataHierarchySampleDataSchema | typeof SaveDataHierarchyDataSchemaSample;
export interface DataService {
}
export interface ColumnSchema {
  label: string;
  dtype: DataType;
}
export const DataStorageInternal = "internal";
export const DataStorageExternal = "external";
export type DataStorage = typeof DataStorageInternal | typeof DataStorageExternal;
export interface DataSchema {
  Id: uuid.UUIDTypes;
  Creator: uuid.UUIDTypes;
  Schema: ColumnSchema[];
  Storage: DataStorage;
  Label: string;
  Description: string;
}
export interface InvalidSampleDataColumnLabels {
  Labels: string[];
}
export const PATTERN = `^[\\w_]+\$`;
export interface DataSchemaCreate {
  Schema: ColumnSchema[];
  Storage: DataStorage;
  Label: string;
  Description: string;
}
export const TABLE_NAME_PREFIX = "data_storage";
export const DATA_STORAGE_TABLE_EXTERNAL_COL_PATH_LABEL = "path";
export const DATA_STORAGE_TABLE_EXTERNAL_COL_FILENAME_LABEL = "filename";
export interface Transform {
  Id: uuid.UUIDTypes;
  Input: uuid.UUIDTypes;
  Output: uuid.UUIDTypes;
  Creator: User;
  Label: string;
  Description: string;
}
export interface DataSchemaResources {
  DataSchema: DataSchema;
  Creator: User;
  Transforms: Transform[];
}
export interface InvalidFileExtensionError {
}
export interface IncompatibleDataSizeError {
}
export interface ColumnData {
  Label: string;
  DType: DataType;
  Values: any[];
}
export interface ParseCsvError {
  Record: number /* uint */;
  Column: number /* int */;
  Err: error;
}
export interface InvalidDataTypeError {
  Value: string;
  DType: DataType;
}
/**
 * StoredData represents teh actual data stored for a sample data.
 * Data is []ColumnData if Storage is `internal`.
 * Data is a string if Storage is `file`.
 */
export interface StoredData {
  SampleData: uuid.UUIDTypes;
  Storage: DataStorage;
  Data: any;
}
export interface SampleDataSchema {
  SampleData: uuid.UUIDTypes;
  DataSchema: uuid.UUIDTypes;
}
export interface DataSchemaRecord {
  Id: uuid.UUIDTypes;
  Storage: DataStorage;
  Schema: ColumnSchema[];
}
export interface SampleDataInfo {
  SampleData: uuid.UUIDTypes;
  Sample: uuid.UUIDTypes;
  DataSchema: uuid.UUIDTypes;
  Timestamp: Date;
}
export interface SampleInfo {
  Id: uuid.UUIDTypes;
  Label: string;
}
export interface DataSchemaRecord {
  Id: uuid.UUIDTypes;
  Label: string;
}
export interface SampleRecord {
  Sample: uuid.UUIDTypes;
  SampleData: uuid.UUIDTypes;
  Label: string;
  Timestamp: Date;
}
export interface ProjectSampleRecord {
  Sample: uuid.UUIDTypes;
  Label: string;
}
export interface SampleDataRecord {
  Id: uuid.UUIDTypes;
  Sample: uuid.UUIDTypes;
  DataSchema: uuid.UUIDTypes;
  Timestamp: Date;
}
export interface DataSchemaRecord {
  Id: uuid.UUIDTypes;
  Label: string;
}
export const SampleDataUserPermissionOwner = "owner";
export const SampleDataUserPermissionRead = "read";
export const SampleDataUserPermissionCreateNote = "create_note";
export const SampleDataUserPermissionModifyProperties = "modify_properties";
export type SampleDataUserPermission = typeof SampleDataUserPermissionOwner | typeof SampleDataUserPermissionRead | typeof SampleDataUserPermissionCreateNote | typeof SampleDataUserPermissionModifyProperties;
export interface SampleDataUserPermissions {
  SampleData: uuid.UUIDTypes;
  Permissions: SampleDataUserPermission[];
}
export interface TransformCreate {
  SourceSchema: uuid.UUIDTypes;
  DestinationSchema: uuid.UUIDTypes;
  Script?: any /* multipart.FileHeader */;
  Label: string;
  Description: string;
}

//////////
// source: project.service.go

export const ProjectPermissionOwner = "owner";
export const ProjectPermissionCreateSample = "create_sample";
export const ProjectPermissionRead = "read";
export type ProjectPermission = typeof ProjectPermissionOwner | typeof ProjectPermissionCreateSample | typeof ProjectPermissionRead;
export const ProjectSamplePermissionModifyLabel = "modify_label";
export const ProjectSamplePermissionModifyTags = "modify_tags";
export const ProjectSamplePermissionModifyProperties = "modify_properties";
export type ProjectSamplePermission = typeof ProjectSamplePermissionModifyLabel | typeof ProjectSamplePermissionModifyTags | typeof ProjectSamplePermissionModifyProperties;
export const VisibilityPublic = "public";
export const VisibilityPrivate = "private";
export type Visibility = typeof VisibilityPublic | typeof VisibilityPrivate;
export interface ProjectService {
}
export interface Project {
  Id: uuid.UUIDTypes;
  Creator: uuid.UUIDTypes;
  Label: string;
  Description: string;
  Visibility: Visibility;
}
export interface ProjectCreate {
  Label: string;
  Description: string;
  Visibility: Visibility;
}
export const PropertyTypeString = "string";
export const PropertyTypeBool = "bool";
export const PropertyTypeUint = "uint";
export const PropertyTypeInt = "int";
export const PropertyTypeFloat = "float";
export const PropertyTypeQuantity = "quantity";
export const PropertyTypeTimestamp = "timestamp";
export type PropertyType = typeof PropertyTypeString | typeof PropertyTypeBool | typeof PropertyTypeUint | typeof PropertyTypeInt | typeof PropertyTypeFloat | typeof PropertyTypeQuantity | typeof PropertyTypeTimestamp;
export interface Property {
  Key: string;
  Type: PropertyType;
  Value: any; // TODO: Match value with type
}
export interface ProjectSampleNote {
  Id: uuid.UUIDTypes;
  Sample: uuid.UUIDTypes;
  Project: uuid.UUIDTypes;
  Creator: uuid.UUIDTypes;
  Timestamp: Date;
  Content: string;
}
export interface ProjectSample {
  Id: uuid.UUIDTypes;
  Creator: uuid.UUIDTypes;
  MembershipCreator: uuid.UUIDTypes;
  MembershipCreated: Date;
  Label: string;
  Tags: string[];
  Properties: Property[];
  NoteCount: number /* uint */;
}
export interface RawDataRecord {
  Id: uuid.UUIDTypes;
  Sample: uuid.UUIDTypes;
  Creator: uuid.UUIDTypes;
  Path: string;
  Type: uuid.UUIDTypes;
  Filename?: string;
  Label?: string;
  Timestamp: Date;
  Visibility: Visibility;
}
export interface DerivedData {
  Parent: uuid.UUIDTypes;
  Transform: uuid.UUIDTypes;
  SampleData: uuid.UUIDTypes;
  Schema: uuid.UUIDTypes;
}
export interface ProjectSampleGroup {
  Id: uuid.UUIDTypes;
  Creator: uuid.UUIDTypes;
  Label: string;
  Description: string;
  Properties: Property[];
  Samples: uuid.UUIDTypes[];
}
export interface SampleGroupRelation {
  Parent: uuid.UUIDTypes;
  Child: uuid.UUIDTypes;
}
export interface ProjectResources {
  Project: Project;
  ProjectTags: string[];
  Samples: ProjectSample[];
  RawData: RawDataRecord[];
  DataSchemas: DataSchema[];
  SampleGroups: ProjectSampleGroup[];
  SampleGroupRelations: SampleGroupRelation[];
  ProjectNoteCount: number /* uint */;
  ProjectPermissions: ProjectPermission[];
}
export interface ProjectSampleInfo {
  Id: uuid.UUIDTypes;
  Tags: string[];
  Properties: Property[];
  NoteCount: number /* uint */;
}
export interface ProjectWithUserPermission {
  Id: uuid.UUIDTypes;
  Creator: uuid.UUIDTypes;
  Label: string;
  Description: string;
  Visibility: Visibility;
  Permissions: ProjectPermission[];
}
export interface FileInfo {
  Name: string;
  Size: number /* int64 */;
  File?: File;
}
export interface ProjectSampleDataCreate {
  Schema: uuid.UUIDTypes;
  File: FileInfo;
  Timestamp: Date;
  Properties: ProjectSampleDataPropertyCreate[];
}
export interface ProjectSampleDataPropertyCreate {
  Key: string;
  Type: PropertyType;
  Value: any; // TODO: match type
}
export interface SampleDataPayloadExternal {
  Path: string;
  Filename: string;
}
export interface ProjectSampleNoteCreate {
  Timestamp: Date;
  Content: string;
}
export interface ProjectSampleCreate {
  Label: string;
  Tags: string[];
  Properties: Property[];
  Data: ProjectSampleDataCreate[];
  Notes: ProjectSampleNoteCreate[];
}
export const NUM_PROPERTY_VALUES = 3;
export const NUM_VALUES_PER_PROPERTY = 4;
export const NUM_NOTE_VALUES = 2;
export const PROJECT_SAMPLE_USER_PERMISSION_COUNT = 3;
export interface ParseSampleDataErrors {
}
export interface ProjectSampleMembershipAsResource {
  Creator: User;
  Timestamp: Date;
  Label: string;
}
export interface SampleUserPermissions {
  User: uuid.UUIDTypes;
  Permissions: SampleUserPermission[];
}
export interface ProjectSampleUserPermissions {
  User: uuid.UUIDTypes;
  Permissions: ProjectSamplePermission[];
}
export interface ProjectSampleResources {
  Id: uuid.UUIDTypes;
  Creator: uuid.UUIDTypes;
  Properties: Property[];
  ProjectMembership: ProjectSampleMembershipAsResource;
  ProjectTags: string[];
  ProjectNotes: ProjectSampleNote[];
  RawData: RawDataRecord[];
  DerivedData: DerivedData[];
  DataSchemas: DataSchema[];
  Users: User[];
  SampleUserPermissions: SampleUserPermissions[];
  ProjectSampleUserPermissions: ProjectSampleUserPermissions[];
}
export interface ProjectSampleNoteUpdate {
  Id: uuid.UUIDTypes;
  Editor: uuid.UUIDTypes;
  Content: string;
}
export interface ProjectSampleUpdate {
  Id: uuid.UUIDTypes;
  Label: string;
  Tags: string[];
  PropertiesUpsert: Property[];
  PropertiesRemove: string[];
  NotesNew: ProjectSampleNoteCreate[];
  NotesUpdate: ProjectSampleNoteUpdate[];
  NotesRemove: uuid.UUIDTypes[];
}
export interface ProjectSampleMembership {
  Project: uuid.UUIDTypes;
  Sample: uuid.UUIDTypes;
  Creator: uuid.UUIDTypes;
  Timestamp: Date;
  Label: string;
}

//////////
// source: sample.service.go

export const SampleUserPermissionOwner = "owner";
export const SampleUserPermissionRead = "read";
export const SampleUserPermissionAddData = "add_data";
export const SampleUserPermissionCreateNote = "create_note";
export const SampleUserPermissionModifyProperties = "modify_properties";
export type SampleUserPermission = typeof SampleUserPermissionOwner | typeof SampleUserPermissionRead | typeof SampleUserPermissionAddData | typeof SampleUserPermissionCreateNote | typeof SampleUserPermissionModifyProperties;
export interface SampleService {
}

//////////
// source: user.service.go

export const AppEmailUrlKey = "app:email:url";
export const AppEmailUsernameKey = "app:email:username";
export const AppEmailPasswordKey = "app:email:password";
export const AppEmailFromKey = "app:email:from";
export const DbPermissionOwner = "owner";
export const DbPermissionAddUser = "add_user";
export const DbPermissionModifyUser = "modify_user";
export const DbPermissionCreateDataSchema = "create_data_schema";
export const DbPermissionModifyDataSchema = "modify_data_schema";
export const DbPermissionCreateTransform = "create_transform";
export const DbPermissionCreateProject = "create_project";
export type DbPermission = typeof DbPermissionOwner | typeof DbPermissionAddUser | typeof DbPermissionModifyUser | typeof DbPermissionCreateDataSchema | typeof DbPermissionModifyDataSchema | typeof DbPermissionCreateTransform | typeof DbPermissionCreateProject;
export const AccountStatusActive = "active";
export const AccountStatusDeactivated = "deactivated";
export type AccountStatus = typeof AccountStatusActive | typeof AccountStatusDeactivated;
export interface UserService {
}
export interface User {
  Id: uuid.UUIDTypes;
  AccountStatus: AccountStatus;
  Email: string;
  Name: string;
  DbPermissions: DbPermission[];
}
export interface UserCreate {
  Email: string;
  Name: string;
  Password: string;
  DbPermissions: DbPermission[];
}
