// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AuthenticateAndGetUser(arg1, arg2) {
  return window['go']['app']['App']['AuthenticateAndGetUser'](arg1, arg2);
}

export function ConnectToDatabase() {
  return window['go']['app']['App']['ConnectToDatabase']();
}

export function CreateProject(arg1) {
  return window['go']['app']['App']['CreateProject'](arg1);
}

export function CreateProjectSamples(arg1, arg2) {
  return window['go']['app']['App']['CreateProjectSamples'](arg1, arg2);
}

export function CreateUser(arg1) {
  return window['go']['app']['App']['CreateUser'](arg1);
}

export function DeactivateUser(arg1) {
  return window['go']['app']['App']['DeactivateUser'](arg1);
}

export function GetAppConfig() {
  return window['go']['app']['App']['GetAppConfig']();
}

export function GetProjectResources(arg1) {
  return window['go']['app']['App']['GetProjectResources'](arg1);
}

export function GetProjectWithUserPermission(arg1) {
  return window['go']['app']['App']['GetProjectWithUserPermission'](arg1);
}

export function GetUserProjects() {
  return window['go']['app']['App']['GetUserProjects']();
}

export function GetUsers() {
  return window['go']['app']['App']['GetUsers']();
}

export function LoadAppConfig() {
  return window['go']['app']['App']['LoadAppConfig']();
}

export function LoadUserFromAuthFile() {
  return window['go']['app']['App']['LoadUserFromAuthFile']();
}

export function Logout() {
  return window['go']['app']['App']['Logout']();
}

export function SaveConfig(arg1) {
  return window['go']['app']['App']['SaveConfig'](arg1);
}

export function UpdateUser(arg1) {
  return window['go']['app']['App']['UpdateUser'](arg1);
}
