// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {uuid} from '../models';

export function AuthenticateAndGetUser(arg1:app.UserCredentials,arg2:boolean):Promise<app.User>;

export function ConnectToDatabase():Promise<app.Ok>;

export function CreateProject(arg1:app.ProjectCreate):Promise<uuid.UUID>;

export function CreateProjectSamples(arg1:uuid.UUID,arg2:Array<app.ProjectSampleCreate>):Promise<app.Ok>;

export function CreateUser(arg1:app.UserCreate):Promise<uuid.UUID>;

export function DeactivateUser(arg1:uuid.UUID):Promise<app.Ok>;

export function GetAppConfig():Promise<app.AppConfig>;

export function GetProjectResources(arg1:uuid.UUID):Promise<app.ProjectResources>;

export function GetProjectWithUserPermission(arg1:uuid.UUID):Promise<app.ProjectWithUserPermission>;

export function GetUserProjects():Promise<Array<app.Project>>;

export function GetUsers():Promise<Array<app.User>>;

export function LoadAppConfig():Promise<app.Ok>;

export function LoadUserFromAuthFile():Promise<app.User>;

export function Logout():Promise<app.Ok>;

export function SaveConfig(arg1:app.AppConfig):Promise<app.Ok>;

export function UpdateUser(arg1:app.User):Promise<app.Ok>;
