// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as uuid$0 from "../../github.com/google/uuid/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AuthenticateAndGetUser(credentials: $models.UserCredentials, remember: boolean): $CancellablePromise<$models.User> {
    return $Call.ByID(3448934749, credentials, remember).then(($result: any) => {
        return $$createType0($result);
    });
}

export function ConnectToDatabase(): $CancellablePromise<$models.Ok> {
    return $Call.ByID(3054858142).then(($result: any) => {
        return $$createType1($result);
    });
}

export function CreateProject(project: $models.ProjectCreate): $CancellablePromise<uuid$0.UUID> {
    return $Call.ByID(689089897, project);
}

export function CreateProjectSamples(project: uuid$0.UUID, samples: $models.ProjectSampleCreate[]): $CancellablePromise<$models.Ok> {
    return $Call.ByID(395745408, project, samples).then(($result: any) => {
        return $$createType1($result);
    });
}

export function CreateUser(user: $models.UserCreate): $CancellablePromise<uuid$0.UUID> {
    return $Call.ByID(1206390855, user);
}

export function DataSchemaCreate(data_schema: $models.DataSchemaCreate): $CancellablePromise<$models.Ok> {
    return $Call.ByID(2840553235, data_schema).then(($result: any) => {
        return $$createType1($result);
    });
}

export function DeactivateUser(user_id: uuid$0.UUID): $CancellablePromise<$models.Ok> {
    return $Call.ByID(412352425, user_id).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetAppConfig(): $CancellablePromise<$models.AppConfig> {
    return $Call.ByID(1365490157).then(($result: any) => {
        return $$createType2($result);
    });
}

export function GetDataSchemas(): $CancellablePromise<$models.DataSchema[]> {
    return $Call.ByID(2775246468).then(($result: any) => {
        return $$createType4($result);
    });
}

export function GetProjectResources(project_id: uuid$0.UUID): $CancellablePromise<$models.ProjectResources> {
    return $Call.ByID(3312231750, project_id).then(($result: any) => {
        return $$createType5($result);
    });
}

export function GetProjectWithUserPermission(project_id: uuid$0.UUID): $CancellablePromise<$models.ProjectWithUserPermission> {
    return $Call.ByID(131050117, project_id).then(($result: any) => {
        return $$createType6($result);
    });
}

export function GetUserProjects(): $CancellablePromise<$models.Project[]> {
    return $Call.ByID(3290360125).then(($result: any) => {
        return $$createType8($result);
    });
}

export function GetUsers(): $CancellablePromise<$models.User[]> {
    return $Call.ByID(2688471908).then(($result: any) => {
        return $$createType9($result);
    });
}

export function LoadAppConfig(): $CancellablePromise<$models.Ok> {
    return $Call.ByID(29814733).then(($result: any) => {
        return $$createType1($result);
    });
}

export function LoadUserFromAuthFile(): $CancellablePromise<$models.User> {
    return $Call.ByID(3160409131).then(($result: any) => {
        return $$createType0($result);
    });
}

export function Logout(): $CancellablePromise<$models.Ok> {
    return $Call.ByID(515391062).then(($result: any) => {
        return $$createType1($result);
    });
}

export function SaveConfig(config: $models.AppConfig): $CancellablePromise<$models.Ok> {
    return $Call.ByID(3992850959, config).then(($result: any) => {
        return $$createType1($result);
    });
}

export function UpdateUser(update: $models.User): $CancellablePromise<$models.Ok> {
    return $Call.ByID(2320279886, update).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = $models.User.createFrom;
const $$createType1 = $models.Ok.createFrom;
const $$createType2 = $models.AppConfig.createFrom;
const $$createType3 = $models.DataSchema.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $models.ProjectResources.createFrom;
const $$createType6 = $models.ProjectWithUserPermission.createFrom;
const $$createType7 = $models.Project.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = $Create.Array($$createType0);
