// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as pgxpool$0 from "../../github.com/jackc/pgx/v5/pgxpool/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AuthenticateAndGetUser(credentials: $models.UserCredentials, remember: boolean, db: pgxpool$0.Pool | null, app_dir: string): $CancellablePromise<$models.User> {
    return $Call.ByID(2560556312, credentials, remember, db, app_dir).then(($result: any) => {
        return $$createType0($result);
    });
}

export function LoadUserFromAuthFile(db: pgxpool$0.Pool | null, app_dir: string): $CancellablePromise<$models.User> {
    return $Call.ByID(2186491458, db, app_dir).then(($result: any) => {
        return $$createType0($result);
    });
}

export function Logout(app_dir: string): $CancellablePromise<void> {
    return $Call.ByID(2575216583, app_dir);
}

// Private type creation functions
const $$createType0 = $models.User.createFrom;
