// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AuthenticateAndGet(credentials: $models.UserCredentials, remember: boolean): $CancellablePromise<$models.User> {
    return $Call.ByID(1111446811, credentials, remember).then(($result: any) => {
        return $$createType0($result);
    });
}

export function Logout(): $CancellablePromise<$models.Ok> {
    return $Call.ByID(2575216583).then(($result: any) => {
        return $$createType1($result);
    });
}

export function UserFromLocal(): $CancellablePromise<$models.User> {
    return $Call.ByID(1130375377).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = $models.User.createFrom;
const $$createType1 = $models.Ok.createFrom;
