// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as uuid$0 from "../../github.com/google/uuid/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function DataSchemaCreate(data_schema: $models.DataSchemaCreate): $CancellablePromise<$models.Ok> {
    return $Call.ByID(2232345692, data_schema).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GetDataSchemasAll(): $CancellablePromise<$models.DataSchema[]> {
    return $Call.ByID(106594542).then(($result: any) => {
        return $$createType2($result);
    });
}

export function GetDataSchemasById(schema_ids: uuid$0.UUID[]): $CancellablePromise<$models.DataSchema[]> {
    return $Call.ByID(3821527915, schema_ids).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetSampleDataStored gets the actual data associated with a sample data entry.
 */
export function GetSampleDataStoredById(sample_data_id: uuid$0.UUID): $CancellablePromise<$models.StoredData> {
    return $Call.ByID(4081438280, sample_data_id).then(($result: any) => {
        return $$createType3($result);
    });
}

export function ParseDataFileToSchema(file_path: string, schema_id: uuid$0.UUID): $CancellablePromise<$models.ColumnData[]> {
    return $Call.ByID(3004645630, file_path, schema_id).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * SaveSampleDataSingle saves a single data to the user's disk.
 * Returns the path the user selected.
 */
export function SaveSampleDataSingle(sample_data_id: uuid$0.UUID): $CancellablePromise<string> {
    return $Call.ByID(2970033972, sample_data_id);
}

// Private type creation functions
const $$createType0 = $models.Ok.createFrom;
const $$createType1 = $models.DataSchema.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $models.StoredData.createFrom;
const $$createType4 = $models.ColumnData.createFrom;
const $$createType5 = $Create.Array($$createType4);
