// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as pgxpool$0 from "../../github.com/jackc/pgx/v5/pgxpool/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AppConfigLoad(app_dir: string): $CancellablePromise<$models.AppConfig> {
    return $Call.ByID(1779261842, app_dir).then(($result: any) => {
        return $$createType0($result);
    });
}

export function AppConfigSave(app_dir: string, config: $models.AppConfig): $CancellablePromise<void> {
    return $Call.ByID(151424231, app_dir, config);
}

export function ConnectToDatabase(url: string, db_name: string, username: string, password: string): $CancellablePromise<pgxpool$0.Pool | null> {
    return $Call.ByID(618300501, url, db_name, username, password).then(($result: any) => {
        return $$createType2($result);
    });
}

// Private type creation functions
const $$createType0 = $models.AppConfig.createFrom;
const $$createType1 = pgxpool$0.Pool.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
