// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as uuid$0 from "../../github.com/google/uuid/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../time/models.js";

export class AppConfig {
    "DbUrl": string;
    "DbUsername": string;
    "DbPassword": string;
    "DbName": string;

    /** Creates a new AppConfig instance. */
    constructor($$source: Partial<AppConfig> = {}) {
        if (!("DbUrl" in $$source)) {
            this["DbUrl"] = "";
        }
        if (!("DbUsername" in $$source)) {
            this["DbUsername"] = "";
        }
        if (!("DbPassword" in $$source)) {
            this["DbPassword"] = "";
        }
        if (!("DbName" in $$source)) {
            this["DbName"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): AppConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AppConfig($$parsedSource as Partial<AppConfig>);
    }
}

export class AppState {

    /** Creates a new AppState instance. */
    constructor($$source: Partial<AppState> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppState instance from a string or object.
     */
    static createFrom($$source: any = {}): AppState {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AppState($$parsedSource as Partial<AppState>);
    }
}

export class ColumnData {
    "Label": string;
    "DType": DataType;
    "Data": any[];

    /** Creates a new ColumnData instance. */
    constructor($$source: Partial<ColumnData> = {}) {
        if (!("Label" in $$source)) {
            this["Label"] = "";
        }
        if (!("DType" in $$source)) {
            this["DType"] = DataType.$zero;
        }
        if (!("Data" in $$source)) {
            this["Data"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ColumnData instance from a string or object.
     */
    static createFrom($$source: any = {}): ColumnData {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Data" in $$parsedSource) {
            $$parsedSource["Data"] = $$createField2_0($$parsedSource["Data"]);
        }
        return new ColumnData($$parsedSource as Partial<ColumnData>);
    }
}

export class ColumnSchema {
    "label": string;
    "dtype": DataType;

    /** Creates a new ColumnSchema instance. */
    constructor($$source: Partial<ColumnSchema> = {}) {
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("dtype" in $$source)) {
            this["dtype"] = DataType.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ColumnSchema instance from a string or object.
     */
    static createFrom($$source: any = {}): ColumnSchema {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ColumnSchema($$parsedSource as Partial<ColumnSchema>);
    }
}

export class DataSchema {
    "Id": uuid$0.UUID;
    "Creator": uuid$0.UUID;
    "Schema": ColumnSchema[];
    "Storage": DataStorage;
    "Label": string;
    "Description": string;

    /** Creates a new DataSchema instance. */
    constructor($$source: Partial<DataSchema> = {}) {
        if (!("Id" in $$source)) {
            this["Id"] = "";
        }
        if (!("Creator" in $$source)) {
            this["Creator"] = "";
        }
        if (!("Schema" in $$source)) {
            this["Schema"] = [];
        }
        if (!("Storage" in $$source)) {
            this["Storage"] = DataStorage.$zero;
        }
        if (!("Label" in $$source)) {
            this["Label"] = "";
        }
        if (!("Description" in $$source)) {
            this["Description"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DataSchema instance from a string or object.
     */
    static createFrom($$source: any = {}): DataSchema {
        const $$createField2_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Schema" in $$parsedSource) {
            $$parsedSource["Schema"] = $$createField2_0($$parsedSource["Schema"]);
        }
        return new DataSchema($$parsedSource as Partial<DataSchema>);
    }
}

export class DataSchemaCreate {
    "Schema": ColumnSchema[];
    "Storage": DataStorage;
    "Label": string;
    "Description": string;

    /** Creates a new DataSchemaCreate instance. */
    constructor($$source: Partial<DataSchemaCreate> = {}) {
        if (!("Schema" in $$source)) {
            this["Schema"] = [];
        }
        if (!("Storage" in $$source)) {
            this["Storage"] = DataStorage.$zero;
        }
        if (!("Label" in $$source)) {
            this["Label"] = "";
        }
        if (!("Description" in $$source)) {
            this["Description"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DataSchemaCreate instance from a string or object.
     */
    static createFrom($$source: any = {}): DataSchemaCreate {
        const $$createField0_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Schema" in $$parsedSource) {
            $$parsedSource["Schema"] = $$createField0_0($$parsedSource["Schema"]);
        }
        return new DataSchemaCreate($$parsedSource as Partial<DataSchemaCreate>);
    }
}

export enum DataStorage {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    DATA_STORAGE_INTERNAL = "internal",
    DATA_STORAGE_FILE = "file",
};

export enum DataType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    DATA_TYPE_STRING = "string",
    DATA_TYPE_INT = "int",
    DATA_TYPE_UINT = "uint",
    DATA_TYPE_FLOAT = "float",
    DATA_TYPE_BOOLEAN = "boolean",
    DATA_TYPE_TIMESTAMP = "timestamp",
};

/**
 * TODO: Should be able to remove as it just mimics `application.FileFilter`
 * but `application.FileFilter` is not exported to the frontend for some reason.
 */
export class FileFilter {
    /**
     * Filter information EG: "Image Files (*.jpg, *.png)"
     */
    "DisplayName": string;

    /**
     * semicolon separated list of extensions, EG: "*.jpg;*.png"
     */
    "Pattern": string;

    /** Creates a new FileFilter instance. */
    constructor($$source: Partial<FileFilter> = {}) {
        if (!("DisplayName" in $$source)) {
            this["DisplayName"] = "";
        }
        if (!("Pattern" in $$source)) {
            this["Pattern"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileFilter instance from a string or object.
     */
    static createFrom($$source: any = {}): FileFilter {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FileFilter($$parsedSource as Partial<FileFilter>);
    }
}

export class Ok {

    /** Creates a new Ok instance. */
    constructor($$source: Partial<Ok> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Ok instance from a string or object.
     */
    static createFrom($$source: any = {}): Ok {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Ok($$parsedSource as Partial<Ok>);
    }
}

export class Project {
    "Id": uuid$0.UUID;
    "Creator": uuid$0.UUID;
    "Label": string;
    "Description": string;
    "Visibility": ProjectVisibility;

    /** Creates a new Project instance. */
    constructor($$source: Partial<Project> = {}) {
        if (!("Id" in $$source)) {
            this["Id"] = "";
        }
        if (!("Creator" in $$source)) {
            this["Creator"] = "";
        }
        if (!("Label" in $$source)) {
            this["Label"] = "";
        }
        if (!("Description" in $$source)) {
            this["Description"] = "";
        }
        if (!("Visibility" in $$source)) {
            this["Visibility"] = ProjectVisibility.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Project instance from a string or object.
     */
    static createFrom($$source: any = {}): Project {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Project($$parsedSource as Partial<Project>);
    }
}

export class ProjectCreate {
    "Label": string;
    "Description": string;
    "Visibility": ProjectVisibility;

    /** Creates a new ProjectCreate instance. */
    constructor($$source: Partial<ProjectCreate> = {}) {
        if (!("Label" in $$source)) {
            this["Label"] = "";
        }
        if (!("Description" in $$source)) {
            this["Description"] = "";
        }
        if (!("Visibility" in $$source)) {
            this["Visibility"] = ProjectVisibility.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProjectCreate instance from a string or object.
     */
    static createFrom($$source: any = {}): ProjectCreate {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProjectCreate($$parsedSource as Partial<ProjectCreate>);
    }
}

export class ProjectResources {
    "Project": Project;
    "ProjectTags": string[];
    "Samples": ProjectSample[];
    "SampleData": SampleData[];
    "DataSchemas": DataSchema[];
    "SampleGroups": ProjectSampleGroup[];
    "SampleGroupRelations": SampleGroupRelation[];
    "ProjectNoteCount": number;
    "ProjectUserPermission": ProjectUserPermission;

    /** Creates a new ProjectResources instance. */
    constructor($$source: Partial<ProjectResources> = {}) {
        if (!("Project" in $$source)) {
            this["Project"] = (new Project());
        }
        if (!("ProjectTags" in $$source)) {
            this["ProjectTags"] = [];
        }
        if (!("Samples" in $$source)) {
            this["Samples"] = [];
        }
        if (!("SampleData" in $$source)) {
            this["SampleData"] = [];
        }
        if (!("DataSchemas" in $$source)) {
            this["DataSchemas"] = [];
        }
        if (!("SampleGroups" in $$source)) {
            this["SampleGroups"] = [];
        }
        if (!("SampleGroupRelations" in $$source)) {
            this["SampleGroupRelations"] = [];
        }
        if (!("ProjectNoteCount" in $$source)) {
            this["ProjectNoteCount"] = 0;
        }
        if (!("ProjectUserPermission" in $$source)) {
            this["ProjectUserPermission"] = ProjectUserPermission.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProjectResources instance from a string or object.
     */
    static createFrom($$source: any = {}): ProjectResources {
        const $$createField0_0 = $$createType3;
        const $$createField1_0 = $$createType4;
        const $$createField2_0 = $$createType6;
        const $$createField3_0 = $$createType8;
        const $$createField4_0 = $$createType10;
        const $$createField5_0 = $$createType12;
        const $$createField6_0 = $$createType14;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Project" in $$parsedSource) {
            $$parsedSource["Project"] = $$createField0_0($$parsedSource["Project"]);
        }
        if ("ProjectTags" in $$parsedSource) {
            $$parsedSource["ProjectTags"] = $$createField1_0($$parsedSource["ProjectTags"]);
        }
        if ("Samples" in $$parsedSource) {
            $$parsedSource["Samples"] = $$createField2_0($$parsedSource["Samples"]);
        }
        if ("SampleData" in $$parsedSource) {
            $$parsedSource["SampleData"] = $$createField3_0($$parsedSource["SampleData"]);
        }
        if ("DataSchemas" in $$parsedSource) {
            $$parsedSource["DataSchemas"] = $$createField4_0($$parsedSource["DataSchemas"]);
        }
        if ("SampleGroups" in $$parsedSource) {
            $$parsedSource["SampleGroups"] = $$createField5_0($$parsedSource["SampleGroups"]);
        }
        if ("SampleGroupRelations" in $$parsedSource) {
            $$parsedSource["SampleGroupRelations"] = $$createField6_0($$parsedSource["SampleGroupRelations"]);
        }
        return new ProjectResources($$parsedSource as Partial<ProjectResources>);
    }
}

export class ProjectSample {
    "Id": uuid$0.UUID;
    "Creator": uuid$0.UUID;
    "MembershipCreator": uuid$0.UUID;
    "MembershipCreated": time$0.Time;
    "Label": string;
    "Tags": string[];
    "Properties": Property[];
    "NoteCount": number;

    /** Creates a new ProjectSample instance. */
    constructor($$source: Partial<ProjectSample> = {}) {
        if (!("Id" in $$source)) {
            this["Id"] = "";
        }
        if (!("Creator" in $$source)) {
            this["Creator"] = "";
        }
        if (!("MembershipCreator" in $$source)) {
            this["MembershipCreator"] = "";
        }
        if (!("MembershipCreated" in $$source)) {
            this["MembershipCreated"] = null;
        }
        if (!("Label" in $$source)) {
            this["Label"] = "";
        }
        if (!("Tags" in $$source)) {
            this["Tags"] = [];
        }
        if (!("Properties" in $$source)) {
            this["Properties"] = [];
        }
        if (!("NoteCount" in $$source)) {
            this["NoteCount"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProjectSample instance from a string or object.
     */
    static createFrom($$source: any = {}): ProjectSample {
        const $$createField5_0 = $$createType4;
        const $$createField6_0 = $$createType16;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Tags" in $$parsedSource) {
            $$parsedSource["Tags"] = $$createField5_0($$parsedSource["Tags"]);
        }
        if ("Properties" in $$parsedSource) {
            $$parsedSource["Properties"] = $$createField6_0($$parsedSource["Properties"]);
        }
        return new ProjectSample($$parsedSource as Partial<ProjectSample>);
    }
}

export class ProjectSampleCreate {
    "Label": string;
    "Tags": string[];
    "Properties": Property[];
    "Data": ProjectSampleDataCreate[];
    "Notes": ProjectSampleNoteCreate[];

    /** Creates a new ProjectSampleCreate instance. */
    constructor($$source: Partial<ProjectSampleCreate> = {}) {
        if (!("Label" in $$source)) {
            this["Label"] = "";
        }
        if (!("Tags" in $$source)) {
            this["Tags"] = [];
        }
        if (!("Properties" in $$source)) {
            this["Properties"] = [];
        }
        if (!("Data" in $$source)) {
            this["Data"] = [];
        }
        if (!("Notes" in $$source)) {
            this["Notes"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProjectSampleCreate instance from a string or object.
     */
    static createFrom($$source: any = {}): ProjectSampleCreate {
        const $$createField1_0 = $$createType4;
        const $$createField2_0 = $$createType16;
        const $$createField3_0 = $$createType18;
        const $$createField4_0 = $$createType20;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Tags" in $$parsedSource) {
            $$parsedSource["Tags"] = $$createField1_0($$parsedSource["Tags"]);
        }
        if ("Properties" in $$parsedSource) {
            $$parsedSource["Properties"] = $$createField2_0($$parsedSource["Properties"]);
        }
        if ("Data" in $$parsedSource) {
            $$parsedSource["Data"] = $$createField3_0($$parsedSource["Data"]);
        }
        if ("Notes" in $$parsedSource) {
            $$parsedSource["Notes"] = $$createField4_0($$parsedSource["Notes"]);
        }
        return new ProjectSampleCreate($$parsedSource as Partial<ProjectSampleCreate>);
    }
}

export class ProjectSampleDataCreate {
    "Schema": uuid$0.UUID;
    "FilePath": string;
    "Timestamp": time$0.Time;
    "Properties": ProjectSampleDataPropertyCreate[];

    /** Creates a new ProjectSampleDataCreate instance. */
    constructor($$source: Partial<ProjectSampleDataCreate> = {}) {
        if (!("Schema" in $$source)) {
            this["Schema"] = "";
        }
        if (!("FilePath" in $$source)) {
            this["FilePath"] = "";
        }
        if (!("Timestamp" in $$source)) {
            this["Timestamp"] = null;
        }
        if (!("Properties" in $$source)) {
            this["Properties"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProjectSampleDataCreate instance from a string or object.
     */
    static createFrom($$source: any = {}): ProjectSampleDataCreate {
        const $$createField3_0 = $$createType22;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Properties" in $$parsedSource) {
            $$parsedSource["Properties"] = $$createField3_0($$parsedSource["Properties"]);
        }
        return new ProjectSampleDataCreate($$parsedSource as Partial<ProjectSampleDataCreate>);
    }
}

export class ProjectSampleDataPropertyCreate {
    "Key": string;
    "Type": PropertyType;

    /**
     * TODO: match type
     */
    "Value": any;

    /** Creates a new ProjectSampleDataPropertyCreate instance. */
    constructor($$source: Partial<ProjectSampleDataPropertyCreate> = {}) {
        if (!("Key" in $$source)) {
            this["Key"] = "";
        }
        if (!("Type" in $$source)) {
            this["Type"] = PropertyType.$zero;
        }
        if (!("Value" in $$source)) {
            this["Value"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProjectSampleDataPropertyCreate instance from a string or object.
     */
    static createFrom($$source: any = {}): ProjectSampleDataPropertyCreate {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProjectSampleDataPropertyCreate($$parsedSource as Partial<ProjectSampleDataPropertyCreate>);
    }
}

export class ProjectSampleGroup {
    "Id": uuid$0.UUID;
    "Creator": uuid$0.UUID;
    "Label": string;
    "Description": string;
    "Properties": Property[];
    "Samples": uuid$0.UUID[];

    /** Creates a new ProjectSampleGroup instance. */
    constructor($$source: Partial<ProjectSampleGroup> = {}) {
        if (!("Id" in $$source)) {
            this["Id"] = "";
        }
        if (!("Creator" in $$source)) {
            this["Creator"] = "";
        }
        if (!("Label" in $$source)) {
            this["Label"] = "";
        }
        if (!("Description" in $$source)) {
            this["Description"] = "";
        }
        if (!("Properties" in $$source)) {
            this["Properties"] = [];
        }
        if (!("Samples" in $$source)) {
            this["Samples"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProjectSampleGroup instance from a string or object.
     */
    static createFrom($$source: any = {}): ProjectSampleGroup {
        const $$createField4_0 = $$createType16;
        const $$createField5_0 = $$createType23;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Properties" in $$parsedSource) {
            $$parsedSource["Properties"] = $$createField4_0($$parsedSource["Properties"]);
        }
        if ("Samples" in $$parsedSource) {
            $$parsedSource["Samples"] = $$createField5_0($$parsedSource["Samples"]);
        }
        return new ProjectSampleGroup($$parsedSource as Partial<ProjectSampleGroup>);
    }
}

export class ProjectSampleNote {
    "Id": uuid$0.UUID;
    "Sample": uuid$0.UUID;
    "Project": uuid$0.UUID;
    "Creator": uuid$0.UUID;
    "Timestamp": time$0.Time;
    "Content": string;

    /** Creates a new ProjectSampleNote instance. */
    constructor($$source: Partial<ProjectSampleNote> = {}) {
        if (!("Id" in $$source)) {
            this["Id"] = "";
        }
        if (!("Sample" in $$source)) {
            this["Sample"] = "";
        }
        if (!("Project" in $$source)) {
            this["Project"] = "";
        }
        if (!("Creator" in $$source)) {
            this["Creator"] = "";
        }
        if (!("Timestamp" in $$source)) {
            this["Timestamp"] = null;
        }
        if (!("Content" in $$source)) {
            this["Content"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProjectSampleNote instance from a string or object.
     */
    static createFrom($$source: any = {}): ProjectSampleNote {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProjectSampleNote($$parsedSource as Partial<ProjectSampleNote>);
    }
}

export class ProjectSampleNoteCreate {
    "Timestamp": time$0.Time;
    "Content": string;

    /** Creates a new ProjectSampleNoteCreate instance. */
    constructor($$source: Partial<ProjectSampleNoteCreate> = {}) {
        if (!("Timestamp" in $$source)) {
            this["Timestamp"] = null;
        }
        if (!("Content" in $$source)) {
            this["Content"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProjectSampleNoteCreate instance from a string or object.
     */
    static createFrom($$source: any = {}): ProjectSampleNoteCreate {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProjectSampleNoteCreate($$parsedSource as Partial<ProjectSampleNoteCreate>);
    }
}

export class ProjectSampleResources {
    "Id": uuid$0.UUID;
    "Creator": uuid$0.UUID;
    "Properties": Property[];
    "ProjectTags": string[];
    "ProjectNotes": ProjectSampleNote[];
    "Data": SampleData[];
    "DataSchemas": DataSchema[];
    "Users": User[];

    /** Creates a new ProjectSampleResources instance. */
    constructor($$source: Partial<ProjectSampleResources> = {}) {
        if (!("Id" in $$source)) {
            this["Id"] = "";
        }
        if (!("Creator" in $$source)) {
            this["Creator"] = "";
        }
        if (!("Properties" in $$source)) {
            this["Properties"] = [];
        }
        if (!("ProjectTags" in $$source)) {
            this["ProjectTags"] = [];
        }
        if (!("ProjectNotes" in $$source)) {
            this["ProjectNotes"] = [];
        }
        if (!("Data" in $$source)) {
            this["Data"] = [];
        }
        if (!("DataSchemas" in $$source)) {
            this["DataSchemas"] = [];
        }
        if (!("Users" in $$source)) {
            this["Users"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProjectSampleResources instance from a string or object.
     */
    static createFrom($$source: any = {}): ProjectSampleResources {
        const $$createField2_0 = $$createType16;
        const $$createField3_0 = $$createType4;
        const $$createField4_0 = $$createType25;
        const $$createField5_0 = $$createType8;
        const $$createField6_0 = $$createType10;
        const $$createField7_0 = $$createType27;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Properties" in $$parsedSource) {
            $$parsedSource["Properties"] = $$createField2_0($$parsedSource["Properties"]);
        }
        if ("ProjectTags" in $$parsedSource) {
            $$parsedSource["ProjectTags"] = $$createField3_0($$parsedSource["ProjectTags"]);
        }
        if ("ProjectNotes" in $$parsedSource) {
            $$parsedSource["ProjectNotes"] = $$createField4_0($$parsedSource["ProjectNotes"]);
        }
        if ("Data" in $$parsedSource) {
            $$parsedSource["Data"] = $$createField5_0($$parsedSource["Data"]);
        }
        if ("DataSchemas" in $$parsedSource) {
            $$parsedSource["DataSchemas"] = $$createField6_0($$parsedSource["DataSchemas"]);
        }
        if ("Users" in $$parsedSource) {
            $$parsedSource["Users"] = $$createField7_0($$parsedSource["Users"]);
        }
        return new ProjectSampleResources($$parsedSource as Partial<ProjectSampleResources>);
    }
}

export enum ProjectUserPermission {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    PROJECT_USER_PERMISSION_READ = "read",
    PROJECT_USER_PERMISSION_READ_WRITE = "read_write",
    PROJECT_USER_PERMISSION_ADMIN = "admin",
    PROJECT_USER_PERMISSION_OWNER = "owner",
};

export enum ProjectVisibility {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    PROJECT_PUBLIC = "public",
    PROJECT_PRIVATE = "private",
};

export class ProjectWithUserPermission {
    "Id": uuid$0.UUID;
    "Creator": uuid$0.UUID;
    "Label": string;
    "Description": string;
    "Visibility": ProjectVisibility;
    "UserPermission": ProjectUserPermission;

    /** Creates a new ProjectWithUserPermission instance. */
    constructor($$source: Partial<ProjectWithUserPermission> = {}) {
        if (!("Id" in $$source)) {
            this["Id"] = "";
        }
        if (!("Creator" in $$source)) {
            this["Creator"] = "";
        }
        if (!("Label" in $$source)) {
            this["Label"] = "";
        }
        if (!("Description" in $$source)) {
            this["Description"] = "";
        }
        if (!("Visibility" in $$source)) {
            this["Visibility"] = ProjectVisibility.$zero;
        }
        if (!("UserPermission" in $$source)) {
            this["UserPermission"] = ProjectUserPermission.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProjectWithUserPermission instance from a string or object.
     */
    static createFrom($$source: any = {}): ProjectWithUserPermission {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProjectWithUserPermission($$parsedSource as Partial<ProjectWithUserPermission>);
    }
}

export class Property {
    "Key": string;
    "Type": PropertyType;

    /**
     * TODO: Match value with type
     */
    "Value": any;

    /** Creates a new Property instance. */
    constructor($$source: Partial<Property> = {}) {
        if (!("Key" in $$source)) {
            this["Key"] = "";
        }
        if (!("Type" in $$source)) {
            this["Type"] = PropertyType.$zero;
        }
        if (!("Value" in $$source)) {
            this["Value"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Property instance from a string or object.
     */
    static createFrom($$source: any = {}): Property {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Property($$parsedSource as Partial<Property>);
    }
}

export enum PropertyType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    PROPERTY_TYPE_STRING = "string",
    PROPERTY_TYPE_BOOL = "bool",
    PROPERTY_TYPE_UINT = "uint",
    PROPERTY_TYPE_INT = "int",
    PROPERTY_TYPE_FLOAT = "float",
    PROPERTY_TYPE_QUANTITY = "quantity",
    PROPERTY_TYPE_TIMESTAMP = "timestamp",
};

export class SampleData {
    "Id": uuid$0.UUID;
    "Sample": uuid$0.UUID;
    "Schema": uuid$0.UUID;
    "Creator": uuid$0.UUID;
    "Timestamp": time$0.Time;

    /** Creates a new SampleData instance. */
    constructor($$source: Partial<SampleData> = {}) {
        if (!("Id" in $$source)) {
            this["Id"] = "";
        }
        if (!("Sample" in $$source)) {
            this["Sample"] = "";
        }
        if (!("Schema" in $$source)) {
            this["Schema"] = "";
        }
        if (!("Creator" in $$source)) {
            this["Creator"] = "";
        }
        if (!("Timestamp" in $$source)) {
            this["Timestamp"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SampleData instance from a string or object.
     */
    static createFrom($$source: any = {}): SampleData {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SampleData($$parsedSource as Partial<SampleData>);
    }
}

export class SampleGroupRelation {
    "Parent": uuid$0.UUID;
    "Child": uuid$0.UUID;

    /** Creates a new SampleGroupRelation instance. */
    constructor($$source: Partial<SampleGroupRelation> = {}) {
        if (!("Parent" in $$source)) {
            this["Parent"] = "";
        }
        if (!("Child" in $$source)) {
            this["Child"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SampleGroupRelation instance from a string or object.
     */
    static createFrom($$source: any = {}): SampleGroupRelation {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SampleGroupRelation($$parsedSource as Partial<SampleGroupRelation>);
    }
}

/**
 * StoredData represents teh actual data stored for a sample data.
 * Data is []ColumnData if Storage is `internal`.
 * Data is a string if Storage is `file`.
 */
export class StoredData {
    "SampleData": uuid$0.UUID;
    "Storage": DataStorage;
    "Data": any;

    /** Creates a new StoredData instance. */
    constructor($$source: Partial<StoredData> = {}) {
        if (!("SampleData" in $$source)) {
            this["SampleData"] = "";
        }
        if (!("Storage" in $$source)) {
            this["Storage"] = DataStorage.$zero;
        }
        if (!("Data" in $$source)) {
            this["Data"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StoredData instance from a string or object.
     */
    static createFrom($$source: any = {}): StoredData {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StoredData($$parsedSource as Partial<StoredData>);
    }
}

export class User {
    "Id": uuid$0.UUID;
    "AccountStatus": string;
    "Email": string;
    "Name": string;
    "Role": UserRole;

    /** Creates a new User instance. */
    constructor($$source: Partial<User> = {}) {
        if (!("Id" in $$source)) {
            this["Id"] = "";
        }
        if (!("AccountStatus" in $$source)) {
            this["AccountStatus"] = "";
        }
        if (!("Email" in $$source)) {
            this["Email"] = "";
        }
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("Role" in $$source)) {
            this["Role"] = UserRole.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new User instance from a string or object.
     */
    static createFrom($$source: any = {}): User {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new User($$parsedSource as Partial<User>);
    }
}

export class UserCreate {
    "Email": string;
    "Name": string;
    "Password": string;
    "Role": string;

    /** Creates a new UserCreate instance. */
    constructor($$source: Partial<UserCreate> = {}) {
        if (!("Email" in $$source)) {
            this["Email"] = "";
        }
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("Password" in $$source)) {
            this["Password"] = "";
        }
        if (!("Role" in $$source)) {
            this["Role"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UserCreate instance from a string or object.
     */
    static createFrom($$source: any = {}): UserCreate {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UserCreate($$parsedSource as Partial<UserCreate>);
    }
}

export class UserCredentials {
    "Email": string;
    "Password": string;

    /** Creates a new UserCredentials instance. */
    constructor($$source: Partial<UserCredentials> = {}) {
        if (!("Email" in $$source)) {
            this["Email"] = "";
        }
        if (!("Password" in $$source)) {
            this["Password"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UserCredentials instance from a string or object.
     */
    static createFrom($$source: any = {}): UserCredentials {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UserCredentials($$parsedSource as Partial<UserCredentials>);
    }
}

export enum UserRole {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    USER_ROLE_OWNER = "owner",
    USER_ROLE_ADMIN = "admin",
    USER_ROLE_USER = "user",
};

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = ColumnSchema.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = Project.createFrom;
const $$createType4 = $Create.Array($Create.Any);
const $$createType5 = ProjectSample.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = SampleData.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = DataSchema.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = ProjectSampleGroup.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = SampleGroupRelation.createFrom;
const $$createType14 = $Create.Array($$createType13);
const $$createType15 = Property.createFrom;
const $$createType16 = $Create.Array($$createType15);
const $$createType17 = ProjectSampleDataCreate.createFrom;
const $$createType18 = $Create.Array($$createType17);
const $$createType19 = ProjectSampleNoteCreate.createFrom;
const $$createType20 = $Create.Array($$createType19);
const $$createType21 = ProjectSampleDataPropertyCreate.createFrom;
const $$createType22 = $Create.Array($$createType21);
const $$createType23 = $Create.Array($Create.Any);
const $$createType24 = ProjectSampleNote.createFrom;
const $$createType25 = $Create.Array($$createType24);
const $$createType26 = User.createFrom;
const $$createType27 = $Create.Array($$createType26);
