// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as uuid$0 from "../../github.com/google/uuid/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../time/models.js";

export class AppConfig {
    "DbUrl": string;
    "DbUsername": string;
    "DbPassword": string;
    "DbName": string;

    /** Creates a new AppConfig instance. */
    constructor($$source: Partial<AppConfig> = {}) {
        if (!("DbUrl" in $$source)) {
            this["DbUrl"] = "";
        }
        if (!("DbUsername" in $$source)) {
            this["DbUsername"] = "";
        }
        if (!("DbPassword" in $$source)) {
            this["DbPassword"] = "";
        }
        if (!("DbName" in $$source)) {
            this["DbName"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): AppConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AppConfig($$parsedSource as Partial<AppConfig>);
    }
}

export class ColumnSchema {
    "label": string;
    "dtype": DataType;

    /** Creates a new ColumnSchema instance. */
    constructor($$source: Partial<ColumnSchema> = {}) {
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("dtype" in $$source)) {
            this["dtype"] = DataType.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ColumnSchema instance from a string or object.
     */
    static createFrom($$source: any = {}): ColumnSchema {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ColumnSchema($$parsedSource as Partial<ColumnSchema>);
    }
}

export class DataSchema {
    "Id": uuid$0.UUID;
    "Creator": uuid$0.UUID;
    "Schema": ColumnSchema[];
    "Storage": Storage;
    "Label": string;
    "Description": string;

    /** Creates a new DataSchema instance. */
    constructor($$source: Partial<DataSchema> = {}) {
        if (!("Id" in $$source)) {
            this["Id"] = "";
        }
        if (!("Creator" in $$source)) {
            this["Creator"] = "";
        }
        if (!("Schema" in $$source)) {
            this["Schema"] = [];
        }
        if (!("Storage" in $$source)) {
            this["Storage"] = Storage.$zero;
        }
        if (!("Label" in $$source)) {
            this["Label"] = "";
        }
        if (!("Description" in $$source)) {
            this["Description"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DataSchema instance from a string or object.
     */
    static createFrom($$source: any = {}): DataSchema {
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Schema" in $$parsedSource) {
            $$parsedSource["Schema"] = $$createField2_0($$parsedSource["Schema"]);
        }
        return new DataSchema($$parsedSource as Partial<DataSchema>);
    }
}

export class DataSchemaCreate {
    "Schema": ColumnSchema[];
    "Storage": Storage;
    "Label": string;
    "Description": string;

    /** Creates a new DataSchemaCreate instance. */
    constructor($$source: Partial<DataSchemaCreate> = {}) {
        if (!("Schema" in $$source)) {
            this["Schema"] = [];
        }
        if (!("Storage" in $$source)) {
            this["Storage"] = Storage.$zero;
        }
        if (!("Label" in $$source)) {
            this["Label"] = "";
        }
        if (!("Description" in $$source)) {
            this["Description"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DataSchemaCreate instance from a string or object.
     */
    static createFrom($$source: any = {}): DataSchemaCreate {
        const $$createField0_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Schema" in $$parsedSource) {
            $$parsedSource["Schema"] = $$createField0_0($$parsedSource["Schema"]);
        }
        return new DataSchemaCreate($$parsedSource as Partial<DataSchemaCreate>);
    }
}

export enum DataType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    DATA_TYPE_STRING = "string",
    DATA_TYPE_INT = "int",
    DATA_TYPE_UINT = "uint",
    DATA_TYPE_FLOAT = "float",
    DATA_TYPE_BOOLEAN = "boolean",
    DATA_TYPE_TIMESTAMP = "timestamp",
};

export type IsoTimestamp = string;

export class Ok {

    /** Creates a new Ok instance. */
    constructor($$source: Partial<Ok> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Ok instance from a string or object.
     */
    static createFrom($$source: any = {}): Ok {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Ok($$parsedSource as Partial<Ok>);
    }
}

export class Project {
    "Id": uuid$0.UUID;
    "Creator": uuid$0.UUID;
    "Label": string;
    "Description": string;
    "Visibility": ProjectVisibility;

    /** Creates a new Project instance. */
    constructor($$source: Partial<Project> = {}) {
        if (!("Id" in $$source)) {
            this["Id"] = "";
        }
        if (!("Creator" in $$source)) {
            this["Creator"] = "";
        }
        if (!("Label" in $$source)) {
            this["Label"] = "";
        }
        if (!("Description" in $$source)) {
            this["Description"] = "";
        }
        if (!("Visibility" in $$source)) {
            this["Visibility"] = ProjectVisibility.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Project instance from a string or object.
     */
    static createFrom($$source: any = {}): Project {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Project($$parsedSource as Partial<Project>);
    }
}

export class ProjectCreate {
    "Label": string;
    "Description": string;
    "Visibility": ProjectVisibility;

    /** Creates a new ProjectCreate instance. */
    constructor($$source: Partial<ProjectCreate> = {}) {
        if (!("Label" in $$source)) {
            this["Label"] = "";
        }
        if (!("Description" in $$source)) {
            this["Description"] = "";
        }
        if (!("Visibility" in $$source)) {
            this["Visibility"] = ProjectVisibility.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProjectCreate instance from a string or object.
     */
    static createFrom($$source: any = {}): ProjectCreate {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProjectCreate($$parsedSource as Partial<ProjectCreate>);
    }
}

export class ProjectResources {
    "Project": Project;
    "ProjectTags": string[];
    "Samples": ProjectSample[];
    "SampleGroups": ProjectSampleGroup[];
    "SampleGroupRelations": SampleGroupRelation[];
    "ProjectNoteCount": number;
    "ProjectUserPermission": ProjectUserPermission;

    /** Creates a new ProjectResources instance. */
    constructor($$source: Partial<ProjectResources> = {}) {
        if (!("Project" in $$source)) {
            this["Project"] = (new Project());
        }
        if (!("ProjectTags" in $$source)) {
            this["ProjectTags"] = [];
        }
        if (!("Samples" in $$source)) {
            this["Samples"] = [];
        }
        if (!("SampleGroups" in $$source)) {
            this["SampleGroups"] = [];
        }
        if (!("SampleGroupRelations" in $$source)) {
            this["SampleGroupRelations"] = [];
        }
        if (!("ProjectNoteCount" in $$source)) {
            this["ProjectNoteCount"] = 0;
        }
        if (!("ProjectUserPermission" in $$source)) {
            this["ProjectUserPermission"] = ProjectUserPermission.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProjectResources instance from a string or object.
     */
    static createFrom($$source: any = {}): ProjectResources {
        const $$createField0_0 = $$createType2;
        const $$createField1_0 = $$createType3;
        const $$createField2_0 = $$createType5;
        const $$createField3_0 = $$createType7;
        const $$createField4_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Project" in $$parsedSource) {
            $$parsedSource["Project"] = $$createField0_0($$parsedSource["Project"]);
        }
        if ("ProjectTags" in $$parsedSource) {
            $$parsedSource["ProjectTags"] = $$createField1_0($$parsedSource["ProjectTags"]);
        }
        if ("Samples" in $$parsedSource) {
            $$parsedSource["Samples"] = $$createField2_0($$parsedSource["Samples"]);
        }
        if ("SampleGroups" in $$parsedSource) {
            $$parsedSource["SampleGroups"] = $$createField3_0($$parsedSource["SampleGroups"]);
        }
        if ("SampleGroupRelations" in $$parsedSource) {
            $$parsedSource["SampleGroupRelations"] = $$createField4_0($$parsedSource["SampleGroupRelations"]);
        }
        return new ProjectResources($$parsedSource as Partial<ProjectResources>);
    }
}

export class ProjectSample {
    "Id": uuid$0.UUID;
    "Creator": uuid$0.UUID;
    "MembershipCreator": uuid$0.UUID;
    "MembershipCreated": time$0.Time;
    "Label": string;
    "Tags": string[];
    "Properties": Property[];
    "NoteCount": number;

    /** Creates a new ProjectSample instance. */
    constructor($$source: Partial<ProjectSample> = {}) {
        if (!("Id" in $$source)) {
            this["Id"] = "";
        }
        if (!("Creator" in $$source)) {
            this["Creator"] = "";
        }
        if (!("MembershipCreator" in $$source)) {
            this["MembershipCreator"] = "";
        }
        if (!("MembershipCreated" in $$source)) {
            this["MembershipCreated"] = null;
        }
        if (!("Label" in $$source)) {
            this["Label"] = "";
        }
        if (!("Tags" in $$source)) {
            this["Tags"] = [];
        }
        if (!("Properties" in $$source)) {
            this["Properties"] = [];
        }
        if (!("NoteCount" in $$source)) {
            this["NoteCount"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProjectSample instance from a string or object.
     */
    static createFrom($$source: any = {}): ProjectSample {
        const $$createField5_0 = $$createType3;
        const $$createField6_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Tags" in $$parsedSource) {
            $$parsedSource["Tags"] = $$createField5_0($$parsedSource["Tags"]);
        }
        if ("Properties" in $$parsedSource) {
            $$parsedSource["Properties"] = $$createField6_0($$parsedSource["Properties"]);
        }
        return new ProjectSample($$parsedSource as Partial<ProjectSample>);
    }
}

export class ProjectSampleCreate {
    "Label": string;
    "Tags": string[];
    "Properties": Property[];
    "Notes": ProjectSampleNoteCreate[];

    /** Creates a new ProjectSampleCreate instance. */
    constructor($$source: Partial<ProjectSampleCreate> = {}) {
        if (!("Label" in $$source)) {
            this["Label"] = "";
        }
        if (!("Tags" in $$source)) {
            this["Tags"] = [];
        }
        if (!("Properties" in $$source)) {
            this["Properties"] = [];
        }
        if (!("Notes" in $$source)) {
            this["Notes"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProjectSampleCreate instance from a string or object.
     */
    static createFrom($$source: any = {}): ProjectSampleCreate {
        const $$createField1_0 = $$createType3;
        const $$createField2_0 = $$createType11;
        const $$createField3_0 = $$createType13;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Tags" in $$parsedSource) {
            $$parsedSource["Tags"] = $$createField1_0($$parsedSource["Tags"]);
        }
        if ("Properties" in $$parsedSource) {
            $$parsedSource["Properties"] = $$createField2_0($$parsedSource["Properties"]);
        }
        if ("Notes" in $$parsedSource) {
            $$parsedSource["Notes"] = $$createField3_0($$parsedSource["Notes"]);
        }
        return new ProjectSampleCreate($$parsedSource as Partial<ProjectSampleCreate>);
    }
}

export class ProjectSampleGroup {
    "Id": uuid$0.UUID;
    "Creator": uuid$0.UUID;
    "Label": string;
    "Description": string;
    "Properties": Property[];
    "Samples": uuid$0.UUID[];

    /** Creates a new ProjectSampleGroup instance. */
    constructor($$source: Partial<ProjectSampleGroup> = {}) {
        if (!("Id" in $$source)) {
            this["Id"] = "";
        }
        if (!("Creator" in $$source)) {
            this["Creator"] = "";
        }
        if (!("Label" in $$source)) {
            this["Label"] = "";
        }
        if (!("Description" in $$source)) {
            this["Description"] = "";
        }
        if (!("Properties" in $$source)) {
            this["Properties"] = [];
        }
        if (!("Samples" in $$source)) {
            this["Samples"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProjectSampleGroup instance from a string or object.
     */
    static createFrom($$source: any = {}): ProjectSampleGroup {
        const $$createField4_0 = $$createType11;
        const $$createField5_0 = $$createType14;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Properties" in $$parsedSource) {
            $$parsedSource["Properties"] = $$createField4_0($$parsedSource["Properties"]);
        }
        if ("Samples" in $$parsedSource) {
            $$parsedSource["Samples"] = $$createField5_0($$parsedSource["Samples"]);
        }
        return new ProjectSampleGroup($$parsedSource as Partial<ProjectSampleGroup>);
    }
}

export class ProjectSampleNoteCreate {
    "Timestamp": IsoTimestamp;
    "Content": string;

    /** Creates a new ProjectSampleNoteCreate instance. */
    constructor($$source: Partial<ProjectSampleNoteCreate> = {}) {
        if (!("Timestamp" in $$source)) {
            this["Timestamp"] = "";
        }
        if (!("Content" in $$source)) {
            this["Content"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProjectSampleNoteCreate instance from a string or object.
     */
    static createFrom($$source: any = {}): ProjectSampleNoteCreate {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProjectSampleNoteCreate($$parsedSource as Partial<ProjectSampleNoteCreate>);
    }
}

export enum ProjectUserPermission {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    PROJECT_USER_PERMISSION_READ = "read",
    PROJECT_USER_PERMISSION_READ_WRITE = "read_write",
    PROJECT_USER_PERMISSION_ADMIN = "admin",
    PROJECT_USER_PERMISSION_OWNER = "owner",
};

export enum ProjectVisibility {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    PROJECT_PUBLIC = "public",
    PROJECT_PRIVATE = "private",
};

export class ProjectWithUserPermission {
    "Id": uuid$0.UUID;
    "Creator": uuid$0.UUID;
    "Label": string;
    "Description": string;
    "Visibility": ProjectVisibility;
    "UserPermission": ProjectUserPermission;

    /** Creates a new ProjectWithUserPermission instance. */
    constructor($$source: Partial<ProjectWithUserPermission> = {}) {
        if (!("Id" in $$source)) {
            this["Id"] = "";
        }
        if (!("Creator" in $$source)) {
            this["Creator"] = "";
        }
        if (!("Label" in $$source)) {
            this["Label"] = "";
        }
        if (!("Description" in $$source)) {
            this["Description"] = "";
        }
        if (!("Visibility" in $$source)) {
            this["Visibility"] = ProjectVisibility.$zero;
        }
        if (!("UserPermission" in $$source)) {
            this["UserPermission"] = ProjectUserPermission.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProjectWithUserPermission instance from a string or object.
     */
    static createFrom($$source: any = {}): ProjectWithUserPermission {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProjectWithUserPermission($$parsedSource as Partial<ProjectWithUserPermission>);
    }
}

export class Property {
    "Key": string;
    "Type": PropertyType;

    /**
     * TODO: Match value with type
     */
    "Value": any;

    /** Creates a new Property instance. */
    constructor($$source: Partial<Property> = {}) {
        if (!("Key" in $$source)) {
            this["Key"] = "";
        }
        if (!("Type" in $$source)) {
            this["Type"] = PropertyType.$zero;
        }
        if (!("Value" in $$source)) {
            this["Value"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Property instance from a string or object.
     */
    static createFrom($$source: any = {}): Property {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Property($$parsedSource as Partial<Property>);
    }
}

export enum PropertyType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    PROPERTY_TYPE_STRING = "string",
    PROPERTY_TYPE_BOOL = "bool",
    PROPERTY_TYPE_UINT = "uint",
    PROPERTY_TYPE_INT = "int",
    PROPERTY_TYPE_FLOAT = "float",
    PROPERTY_TYPE_QUANTITY = "quantity",
    PROPERTY_TYPE_TIMESTAMP = "timestamp",
};

export class SampleGroupRelation {
    "Parent": uuid$0.UUID;
    "Child": uuid$0.UUID;

    /** Creates a new SampleGroupRelation instance. */
    constructor($$source: Partial<SampleGroupRelation> = {}) {
        if (!("Parent" in $$source)) {
            this["Parent"] = "";
        }
        if (!("Child" in $$source)) {
            this["Child"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SampleGroupRelation instance from a string or object.
     */
    static createFrom($$source: any = {}): SampleGroupRelation {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SampleGroupRelation($$parsedSource as Partial<SampleGroupRelation>);
    }
}

export enum Storage {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    STORAGE_INTERNAL = "internal",
    STORAGE_FILE = "file",
};

export class User {
    "Id": uuid$0.UUID;
    "AccountStatus": string;
    "Email": string;
    "Name": string;
    "Role": UserRole;

    /** Creates a new User instance. */
    constructor($$source: Partial<User> = {}) {
        if (!("Id" in $$source)) {
            this["Id"] = "";
        }
        if (!("AccountStatus" in $$source)) {
            this["AccountStatus"] = "";
        }
        if (!("Email" in $$source)) {
            this["Email"] = "";
        }
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("Role" in $$source)) {
            this["Role"] = UserRole.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new User instance from a string or object.
     */
    static createFrom($$source: any = {}): User {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new User($$parsedSource as Partial<User>);
    }
}

export class UserCreate {
    "Email": string;
    "Name": string;
    "Password": string;
    "Role": string;

    /** Creates a new UserCreate instance. */
    constructor($$source: Partial<UserCreate> = {}) {
        if (!("Email" in $$source)) {
            this["Email"] = "";
        }
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("Password" in $$source)) {
            this["Password"] = "";
        }
        if (!("Role" in $$source)) {
            this["Role"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UserCreate instance from a string or object.
     */
    static createFrom($$source: any = {}): UserCreate {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UserCreate($$parsedSource as Partial<UserCreate>);
    }
}

export class UserCredentials {
    "Email": string;
    "Password": string;

    /** Creates a new UserCredentials instance. */
    constructor($$source: Partial<UserCredentials> = {}) {
        if (!("Email" in $$source)) {
            this["Email"] = "";
        }
        if (!("Password" in $$source)) {
            this["Password"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UserCredentials instance from a string or object.
     */
    static createFrom($$source: any = {}): UserCredentials {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UserCredentials($$parsedSource as Partial<UserCredentials>);
    }
}

export enum UserRole {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    USER_ROLE_OWNER = "owner",
    USER_ROLE_ADMIN = "admin",
    USER_ROLE_USER = "user",
};

// Private type creation functions
const $$createType0 = ColumnSchema.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = Project.createFrom;
const $$createType3 = $Create.Array($Create.Any);
const $$createType4 = ProjectSample.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = ProjectSampleGroup.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = SampleGroupRelation.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = Property.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = ProjectSampleNoteCreate.createFrom;
const $$createType13 = $Create.Array($$createType12);
const $$createType14 = $Create.Array($Create.Any);
