// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as uuid$0 from "../../github.com/google/uuid/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CreateProject(project: $models.ProjectCreate): $CancellablePromise<uuid$0.UUID> {
    return $Call.ByID(725581675, project);
}

export function CreateProjectSamples(project: uuid$0.UUID, samples: $models.ProjectSampleCreate[]): $CancellablePromise<$models.Ok> {
    return $Call.ByID(13139318, project, samples).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GetProjectResources(project_id: uuid$0.UUID): $CancellablePromise<$models.ProjectResources> {
    return $Call.ByID(4150479404, project_id).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetProjectSampleResources(project_id: uuid$0.UUID, sample_id: uuid$0.UUID): $CancellablePromise<$models.ProjectSampleResources> {
    return $Call.ByID(2454335910, project_id, sample_id).then(($result: any) => {
        return $$createType2($result);
    });
}

export function GetProjectWithUserPermission(project_id: uuid$0.UUID): $CancellablePromise<$models.ProjectWithUserPermission> {
    return $Call.ByID(328045959, project_id).then(($result: any) => {
        return $$createType3($result);
    });
}

export function GetUserProjects(): $CancellablePromise<$models.Project[]> {
    return $Call.ByID(2955955071).then(($result: any) => {
        return $$createType5($result);
    });
}

// Private type creation functions
const $$createType0 = $models.Ok.createFrom;
const $$createType1 = $models.ProjectResources.createFrom;
const $$createType2 = $models.ProjectSampleResources.createFrom;
const $$createType3 = $models.ProjectWithUserPermission.createFrom;
const $$createType4 = $models.Project.createFrom;
const $$createType5 = $Create.Array($$createType4);
