// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as uuid$0 from "../../github.com/google/uuid/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CreateUser(user: $models.UserCreate): $CancellablePromise<uuid$0.UUID> {
    return $Call.ByID(4078737311, user);
}

export function DeactivateUser(user_id: uuid$0.UUID): $CancellablePromise<$models.Ok> {
    return $Call.ByID(3769408913, user_id).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GetUsers(): $CancellablePromise<$models.User[]> {
    return $Call.ByID(1137183740).then(($result: any) => {
        return $$createType2($result);
    });
}

export function UpdateUser(update: $models.User): $CancellablePromise<$models.Ok> {
    return $Call.ByID(2606112134, update).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = $models.Ok.createFrom;
const $$createType1 = $models.User.createFrom;
const $$createType2 = $Create.Array($$createType1);
