// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AuthenticateAndGetUser(arg1, arg2) {
  return window['go']['main']['App']['AuthenticateAndGetUser'](arg1, arg2);
}

export function ConnectToDatabase() {
  return window['go']['main']['App']['ConnectToDatabase']();
}

export function CreateSampleGroup(arg1) {
  return window['go']['main']['App']['CreateSampleGroup'](arg1);
}

export function CreateUser(arg1) {
  return window['go']['main']['App']['CreateUser'](arg1);
}

export function GetAppConfig() {
  return window['go']['main']['App']['GetAppConfig']();
}

export function GetRecentSampleGroupsWithSamples() {
  return window['go']['main']['App']['GetRecentSampleGroupsWithSamples']();
}

export function LoadAppConfig() {
  return window['go']['main']['App']['LoadAppConfig']();
}

export function LoadUser() {
  return window['go']['main']['App']['LoadUser']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}
