// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {uuid} from '../models';

export function AuthenticateAndGetUser(arg1:main.UserCredentials,arg2:boolean):Promise<main.User>;

export function ConnectToDatabase():Promise<main.Ok>;

export function CreateSampleGroup(arg1:main.SampleGroupCreate):Promise<main.Ok>;

export function CreateUser(arg1:main.UserCreate):Promise<uuid.UUID>;

export function GetConfig():Promise<main.AppConfig>;

export function GetRecentSampleGroupsWithSamples():Promise<Array<main.Sample>>;

export function LoadUser():Promise<main.User>;

export function SaveConfig(arg1:main.AppConfig):Promise<main.Ok>;
